### ISSUE TITLE
Edge configuration dialog is not clear

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Core#103]
I have L-FilesToScp followed by L-FilesToVirtuoso connected by an edge. It is red - something needs to be specified. When I open the config dialog, it is empty so it is not clear what should I fill in. When I click "Is run after edge", the red color changes to black and it is OK. If "Is run after edge" must be checked in this case of DPUs, it should be by default

![image](https://cloud.githubusercontent.com/assets/4235208/3844073/baca4fbe-1e45-11e4-9f34-f59764b8f178.png)

**Comment by skrchnavy** [comment]
related to #250
