### ISSUE TITLE
Option to propagate DPU template settings to all/selected instances

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#132]
All DPU instances should have an option to choose
1) whether they should have the same settings as the template they come from - when template settings changes, so does theirs
2) whether they should have their own settings - when DPU template settings changes, their does not.

This should be realized by a checkbox that switches this behavior.

Minimalistic version is a button that propagates template settings to all instances. It can use the DPU template ID in the following simple SQL query:
<pre><code>UPDATE unifiedviews.dpu_instance AS t JOIN unifiedviews.dpu_template AS s on s.id = &lt;DPU TEMPLATE ID&gt;
 SET t.configuration = s.configuration
 WHERE t.dpu_id = s.id;</code></pre>

**Comment by skrchnavy** [comment]
fixed in beec69cef428976073f8f1795f5dd32e33c63af7
