### ISSUE TITLE
Frontend: When scrolling canvas and editing, DPU positions are changed

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#135]
![image](https://cloud.githubusercontent.com/assets/718827/4027441/c54f24d6-2c2e-11e4-8414-e06c0f1ddb8a.png)

The circled DPUs moved when I was scrolling, adding DPUs and saving the pipeline (probably happened when Save was clicked). There has to be a bug with DPU position computation in combination with Canvas scrolling

**Comment by tomas-knap** [comment]
Won't fix as new version of canvas is being planned
