### ISSUE TITLE
Problem with empty query result in debug mode

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Core#142]
When I run a query in the debug mode with an empty result, an error occurs. However, only in Chrome.

For example, I run the following query:

'''PREFIX sukl: <http://linked.opendata.cz/ontology/sukl/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?mpp
    sukl:hasPriceSpecification ?price .
  
  ?price a gr:PriceSpecification ;
    gr:hasCurrency "CZK" ;
    gr:valueAddedTaxIncluded "true"^^xsd:boolean ;
    gr:hasCurrencyValue ?priceValue ;
    gr:validFrom ?validFrom ;
    gr:validThrough ?validThrough .

    
}
FROM <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/804/dpu/553/du/1>
WHERE {
  ?mpp
    skos:notation ?notation ;
    sukl:col86 ?priceValue .
  
  BIND(STRDT("20130101", xsd:date) AS ?validFrom)
  BIND(STRDT("20130104", xsd:date) AS ?validThrough)

  BIND(IRI(CONCAT(STR(?mpp), "/price/", ?validFrom)) AS ?price )
      
}
LIMIT 50''''

on the output of DPU "Medicinal Product Packaging basic RDF representation" in pipeline https://cuni-test1.comsode.eea.sk/unifiedviews/#!PipelineEdit/63 ([EH_11] Prices of medicinal products from Czech SIDC [OLD]) (run 27.8.2014 8:41:30). The result in Chrome is:

![image](https://cloud.githubusercontent.com/assets/4235208/4056489/cb352ea2-2dbb-11e4-8f4b-6a23f3c3079f.png)

In Firefox, the result is OK:

![image](https://cloud.githubusercontent.com/assets/4235208/4056494/d4b7b166-2dbb-11e4-86d4-a9b176b3e206.png)

**Comment by tomas-knap** [comment]
Was not able to reproduce. Tested on Chrome 43.0.2357.134 (64-bit)
