### ISSUE TITLE
DPUs to run in pipeline should maintain order among individual runs

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#147]
DPUs run in a random order in each run. This is very hard to debug, see screenshot where it is not clear how the DPUs ran after each other, when they are not named individually.
![image](https://cloud.githubusercontent.com/assets/718827/4115061/33e45a8a-3272-11e4-9f26-65b6cd59ab53.png)

**Comment by tomas-knap** [comment]
Current situation: The graph of the execution is build dynamically everytime pipeline is executed

**Comment by skrchnavy** [comment]
Is there a possibility to calculate order dynamically but using algorithm that calculate same order of the DPU instances when no change between runs done in pipeline?

**Comment by tomas-knap** [comment]
Well, standard BFS is used to traverse dependency graph. So the traversing may be adjusted, so that certain key is used for sorting the children of the node before putting them on the stack.

**Comment by tomas-knap** [comment]
@skrchnavy I would suggest to remove this from 2.2.0, as this is not that pressing.
