### ISSUE TITLE
New DPU Type: Quality (Yellow)

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#162]
Add fourth DPU type, Quality.
This means adding the @AsQuality annotation to DPUs and assign it in frontend.

**Comment by skrchnavy** [comment]
API updated in UnifiedViews/Plugin-DevEnv@48dcb73baed0ecb1f5b057779e13420c185ad7db
and implementation df9699055eff84a6146cd994afdc534b162e4798
