### ISSUE TITLE
Scheduler runs daily scheduled pipelines one day early

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#166]
When I schedule a pipeline to run "daily" at midnight, I expect it to first run later, at midnight. Instead, it runs immediately and then is scheduled as expected.
![image](https://cloud.githubusercontent.com/assets/718827/4205301/3bf39b3c-383f-11e4-8742-79168cd03938.png)

**Comment by mbl-eea-sk** [comment]
After more attempts I have not noticed any inconvenience. No process was launched immediatelly.

![schedule](https://cloud.githubusercontent.com/assets/12254192/8927382/56b65ce0-3517-11e5-8416-47377c2bc4a2.png)

![runs](https://cloud.githubusercontent.com/assets/12254192/8927383/56b6c108-3517-11e5-8232-c62288cfcc3b.png)

**Comment by tomas-knap** [comment]
It behaves reasonably, when I select to run "daily", first it is planned for the actual date & time, which is ok.
