### ISSUE TITLE
Revert styling of the top part of UV

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#170]
Revert styling of the top part of UV. The logo does not have to be there, the spaces all around dont have to be there. What is more important? Logo or space to develop pipelines?!
![image](https://cloud.githubusercontent.com/assets/718827/4248371/b40950f8-3a65-11e4-84bc-6ab1a650172f.png)

**Comment by skrchnavy** [comment]
fixed in e54bfd186a8cd77c9a7ae8e70b96fb0c93177975
merged into develop branch via virtuoso merge 25287fecc2c1841e4c971c14e42a103dbf8be76c

**Comment by skrchnavy** [comment]
closed - to be included into v1.6.0
