### ISSUE TITLE
Import/export: improve handling of parent/child templates

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#177]
Target:
![image](https://cloud.githubusercontent.com/assets/718827/4303334/2497e58e-3e65-11e4-979a-ca7c8ac035ba.png)
Source:
![image](https://cloud.githubusercontent.com/assets/718827/4303340/34388b9c-3e65-11e4-9e7d-a1b6ce0bbd25.png)

It would be better to detect that there is the "parent" DPU missing in the export (e.g. by tagging child DPU templates) and create it the same way as when I would import the JAR in question with default settings so that child templates remain child and the parent one has default settings

**Comment by tomas-knap** [comment]
@jakubklimek Is this still relevant?

**Comment by jakubklimek** [comment]
Yes, there was no improvement of export/import

**Comment by tomas-knap** [comment]
@tomas-knap Discuss with Jakub his idea. 

I would suggest to keep it simple. If 3rd level DPU is exported, but target system does not involve required 2nd level DPU, the import will fail. When importing, 2nd level DPUs should be imported first.

**Comment by skrchnavy** [comment]
@tomas-knap how do you know that you have 2nd level DPU already imported? (Be aware of possibility to rename 2nd level template).

**Comment by tomas-knap** [comment]
Closing.

It will work in a way that: If 3rd level DPU template is exported, 2nd level is exported as well (so it cannot happen that there is 3rd level DPU exported without 2nd level DPU). During import, see #356 and the user stories referred there.
