### ISSUE TITLE
execution monitor: problem when an execution is finishing.

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#179]
I observer strange behavior in execution monitor.

Scenario:
a execution no. 1 is running 
a execution no. 1 is about to finish and it prints "finished with warning" into log output. I suppose that it means the execution 1 is finished, but the execution seems to running. 
when I run an execution no. 2 then the execution no. 1 finishes immediately.

**Comment by tomas-knap** [comment]
cannot be reproduced
