### ISSUE TITLE
When configuration is not saved for any reason, it is erased

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#18]
When configuring a DPU and clicking save, when there is an error and configuration is not saved (e.g. missing SPARQL prefix), all configuration is erased and has to be input again.

**Comment by tomas-knap** [comment]
This was already solved in UV 2.1 - there was inconsistency in the behavior when saving "invalid" configuration. Now this is unified and in case of problems in the conf, the conf is not erased.
