### ISSUE TITLE
Unreachable bottom of menu in DPU templates view

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Core#180]
In Firefox Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0
See the picture, I cannot catch the last one item in menu.

![unreachable2](https://cloud.githubusercontent.com/assets/6399320/4331203/87cc8c66-3fc0-11e4-810b-3fb799fd5da1.png)

**Comment by tomas-knap** [comment]
cannot reproduce
