### ISSUE TITLE
Serious concurrency problem

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#183]
There is a concurrency problem somewhere in UV. When even a few pipelines are running, everything (pipelines themselves, frontend) gets slow even though CPU usage is below 10%, memory is free, disk and network usage is low. This is becoming a serious problem as the number of pipelines grows.

**Comment by tomas-knap** [comment]
@jakubklimek Was the problem the intensive logging?

**Comment by jakubklimek** [comment]
No, the problem was disk overload by RDF operations
