### ISSUE TITLE
Export pipeline does not close the export window

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#186]
When I click on export in the export pipeline window, it is not closed.

**Comment by skrchnavy** [comment]
shall be done as a part of #356

**Comment by mvi-eea-sk** [comment]
Same with exporting all dpu templates

**Comment by skrchnavy** [comment]
this is fixed in develop branch so just quick review and then it can be closed when OK.

**Comment by tomas-knap** [comment]
Tested, ok.
