### ISSUE TITLE
Import\Export not working, jar file name mapping

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#193]
I have exported [MICR_1] Gov.cz- Instituce from cuni-test1. Now when I try to import it into cuni-test2 I got missing DPU with jat file name uv-l-filesToVirtuoso-1.3.1.jar.

But when I search DPU Templates on cuni-test2 I find filesToVirtuoso with uv-l-filesToVirtuoso/uv-l-filesToVirtuoso-1.3.1.jar.

I also face similar problem with my Vavai pipelines, but this is better example for replication I believe.

**Comment by tomas-knap** [comment]
As described in https://team.eea.sk/wiki/pages/viewpage.action?pageId=113837857, it will behave in a way that pipelines requiring older version of the DPU may be imported to the system using newer version but not vice versa. This is covered by #357

Different versions not supported. 

Closing this issue.
