### ISSUE TITLE
override installed dpus

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#197]
I want to upgrade all installed dpus

There should be easy way how to do it.

**Comment by skrchnavy** [comment]
@eea02 / @Jan-Marcek  / @peterklimo - isn't this already supported via master API?

**Comment by eea02** [comment]
Upgrade of installed DPU: yes, it is supported by API, but removal not.

**Comment by skrchnavy** [comment]
@Jan-Marcek what is intention to support delete all functionality?

**Comment by Jan-Marcek** [comment]
I'm not certain after almost 1 year...I was unable to upgrade dpu -> I had to delete and import dpu/pipelines. Imagine that you have 20 dpu. I think we could mark case "delete all dpus/pipeline" as invalid.

**Comment by Jan-Marcek** [comment]
@tomas-knap  override installed dpus is fixed. please, change label
