### ISSUE TITLE
New pipeline cannot be run twice?

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#204]
No conflicts are defined. However, when a pipeline is running, I cannot run it for the second time.

This happend when we were migrating the logs table. First run of the pipeline was finished, waiting on the log flush. I tried to run it for the second time and...

![image](https://cloud.githubusercontent.com/assets/718827/4675858/4870039a-55d2-11e4-8af6-2e5fc41d18e2.png)

**Comment by skrchnavy** [comment]
@tomas-knap to propose solution or the downgrade priority
