### ISSUE TITLE
Unified Views internalization support

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#217]
To be able to install UnifiedViews at non English speaking customers, it is requested to support different languages in UnifiedViews.

This task is request for internalisation support in GUI (frontend)

**Comment by eea02** [comment]
Feature ready for review: 0a80b058ac7615b788b679ae39ffe91ecbe19de8

**Comment by tomas-knap** [comment]
There is comment to be considered before being approved, see: https://github.com/UnifiedViews/Core/pull/281

**Comment by skrchnavy** [comment]
#281 closed
