### ISSUE TITLE
New Feature: FilesDataUnit debugging

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#221]
This should include (and feel free to contribute):
- list and filter files
- download files (single, multiple, selected as zip, input list of files to download as zip)
- view as text

**Comment by tomas-knap** [comment]
Extends #266

**Comment by tomas-knap** [comment]
Regarding specification, please consult with @tomas-knap

**Comment by tomas-knap** [comment]
I adjusted #266, so this issue is a duplicate
