### ISSUE TITLE
Dangerous debug button in the DPU context menu

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Core#224]
The debug button in the context menu of a DPU is dangerous - sometimes I unintentionally click on it and start debuging. I would like to see a dialog which asks me if I really want to do the debug.

![image](https://cloud.githubusercontent.com/assets/4235208/4899365/0a3f9fb6-641b-11e4-9cb2-f1ce5bf26007.png)

**Comment by tomas-knap** [comment]
@jakubklimek @martinnec  Is this still wanted feature? From my perspective, it is ok as it now - no extra confirmation messages.
