### ISSUE TITLE
Incorrect last execution time and status of a pipeline in the pipelines list

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Core#225]
There is a mismatch between the last execution time and status in the list of pipelines and in the execution monitor. E.g. 

"[EH_11] Prices of medicinal products from Czech SIDC (Metadata)" according to the pipelines list run at 15:23 for the last time and ended with an error:

![image](https://cloud.githubusercontent.com/assets/4235208/4899398/8fa682d2-641b-11e4-9cd0-8b2a2b48a804.png)

However, in the execution monitor, there is the last run of the pipeline at 18:25 and with success (which is correct, the time and status in the pipelines list is not correct):

![image](https://cloud.githubusercontent.com/assets/4235208/4899448/277008ea-641c-11e4-86bb-c62db0a7e8b3.png)

**Comment by mbl-eea-sk** [comment]
This seems to work fine, both views use the same method to get the last running time:

https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/components/PipelineStatus.java#L107
https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/container/accessor/PipelineAccessor.java#L171
