### ISSUE TITLE
T-metadata and T-sparql very slow - Core/Storage performance problem - Problem with too many graphs in the query

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#226]
I had a suspicion for a long time but today I confirmed it. There is some kind of problem maybe with t-metadata and t-sparql, but more likely it seems like a Core or even Storage issue, becasue from the code there is not much that could be improved in t-metadata - On https://github.com/UnifiedViews/Plugins/blob/master/t-metadata/src/main/java/eu/unifiedviews/plugins/transformer/metadata/Metadata.java#L250 T-metadata issues 6 basic SPARQL queries to compute statistics. These queries take a VERY long time, depending on the size of data. For the RUIAN dataset (600M triples), the first (or maybe first two) queries run for 2 days now and counting, Sesame storage is taking approx. 125% of CPU for the whole time.

I issued the same 6 queries in our Virtuoso instance of this dataset, running on a 16GB RAM machine, and all 6 together were computed within an hour.

This means that the whole RUIAN pipeline is doable (outside of UnifiedViews) in approx. 15 hours.

I suggest loading the RUIAN data to a standalone Sesame and issuing these queries to rule out Core problems. Then, I suggest switching to Virtuoso (which means dealing with the storage-per-UV problem and possible Virtuoso bugs).

**Comment by skrchnavy** [comment]
@pshoda / @jakubklimek : please confirm that this is solved in virtuoso feature branch

**Comment by jakubklimek** [comment]
Not really. There is a workaround for specific cases ("per-graph" execution in t-sparqlConstruct & t-sparqlUpdate followed by a graph merger and then t-metadata) but generally the problem is that when there is a larger number of graphs (hundreds and more) the triplestore (both sesame and virtuoso) is unable to process a query with so many FROM clauses or graphs set in the Dataset.

**Comment by tomas-knap** [comment]
Closed, as it duplicates: https://github.com/UnifiedViews/Core/issues/188
