### ISSUE TITLE
Frontend: Clickable list items bug

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#231]
In all Vaadin lists when a click on an item is supposed to trigger an action, there is the following problem:
1) Click on the item triggering the action
2) Go back, the item is still selected
3) Click on the item, it gets deselected and the action is not triggered.
4) I need to click it again to trigger the action.

This happens with logs, pipelines, etc.

**Comment by tomas-knap** [comment]
Yes, this is quite annoying issues. 

Solution: When I click on the pipeline, it is opened. If I return back to Pipeline list, NO pipeline should be selected. Similary for other tables (executions, schedule records)

**Comment by eea03** [comment]
The described issue has been fixed;

However, there still remains similar issue for execution view, logs and messages:
When user clicks e.g. on execution, details are shown. When user clicks again on the same execution, in table it is deselected, but the detail is still displayed for this execution (similarly with logs and messages window details); 
This can be quite confusing for user as the view is inconsistent

I would suggest one of the 2 solutions:
- close / hide details when already selected item is selected (=deselected) 
- do not deselect item in table, so item is still selected in table and details are shown which is consistent

**Comment by skrchnavy** [comment]
for v2.0.3 this has to be also ported (cherrypicked if possible into hotfix branch for 2.0.3

**Comment by tomas-knap** [comment]
To finish this issue: Yes, when user clicks on event/log in pipeline execution detail, detail of the message is shown. If the user clicks once again on that record, nothing happens, it is NOT deselected. 

Note: As I was testing it, it seems to be working in that way already for execution records.

**Comment by eea03** [comment]
I just tested it in Chrome and Firefox and it is behaving like i described.
Just to be sure, deselecting means that it is not highlighted in table anymore.

And as I was testing, this still is issue for logs and events and also for executions (if you click on pipeline name, then it behaves correctly)

**Comment by skrchnavy** [comment]
@eea03 please finalize the issue

**Comment by eea03** [comment]
First a decision has to be made what to do with this issue I am describing. 
I agree it is not as annoying as the already fixed issue, but still when execution / log / event detail is displayed and no entry in the table is highlighted, it is not a consistent view.

When detail is displayed, corresponding entry in table should always be highlighted
@tomas-knap says he does not observe such behavior but I have tested it on 3 different UV instances and behavior was always wrong (as I described)

So after first click:
![executions_highlighted](https://cloud.githubusercontent.com/assets/10461994/8231382/5ffeb612-15c8-11e5-80d8-0d5ca34d8999.png)

After clicking again on the same entry:
![executions_clicked_again](https://cloud.githubusercontent.com/assets/10461994/8231388/73016354-15c8-11e5-9f66-e769760f1ab8.png)

**Comment by eea03** [comment]
After discussing with @skrchnavy, descision has been made how to solve the described issue: 
After clicking on already selected entry in table, entry will stay highlighted in table
