### ISSUE TITLE
Specify version of UV-Core in frontend 

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#232]
Add tab with version numbers of Core and libraries in frontend, so that it is clear which version of what is deployed.

**Comment by tomas-knap** [comment]
It should be clear from which version/commit the deployed UV frontend was built.

**Comment by peterklimo** [comment]
my proposal:
1. file version.properties where we define following property
version=[[version]]
2. version will be displayed on the front page,we need to adapt the code to read version.properties file
3. placeholder in the properties file will be replaced during build procedure with actual version from pom.xml

**Comment by peterklimo** [comment]
11276ec
