### ISSUE TITLE
Do something with logging sql errors

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Core#233]
Try DROP TABLE logging;
Of course, it is error state, but for simulation it is ok. The backend component in my estimation, was able to fill up disk in two days (over 2G of logs). The logs were rotated properly, but they were not erased as the min keep days was not reached at all.
Can something be done with SQL error intensive logging?

**Comment by tomas-knap** [comment]
There is a possibility to set up how long logs for backend/frontend should be kept. For the production instance at uv.opendata.cz (tens of pipelines running daily), there is 7days log rotate and 12GB of logs. So for frontend/backend logs, the current solution is enough, certain fine tuning may be done anytime but we have more serious issues to be solved
