### ISSUE TITLE
Analyze "Delete debug resources"

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#238]
It does not delete the temp directories .. what does this functionality do right now and more importantly does it work?

**Comment by skodape** [comment]
This functionality was obsolete and would not work with current data units design.

Related code should be removed from 
https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/container/rdf/RepositoryFrontendHelper.java

function deleteApplicationGraphs. In future other method (execution based?) for debug data deletion may be implement. If require other issue should  be used.

**Comment by tomas-knap** [comment]
To be done: Remove the code described in the previous comment by Petyr, check that frontend does not contain button "deleteDebugResources" in Settings. Then close. Will be reimplemented in the future

**Comment by tomas-knap** [comment]
Duplicates https://github.com/UnifiedViews/Core/issues/359
