### ISSUE TITLE
Bad DPU Template configuration dialog formatting

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#239]
![image](https://cloud.githubusercontent.com/assets/718827/5024576/a54848ee-6b0c-11e4-9b6f-4d6d1f46fbf5.png)

The Query box does not expand. This is probably similar in other DPUs, however, has to do with handling in Frontend - when the configuration opens in a window (in a pipeline), it is OK.

**Comment by tomas-knap** [comment]
Verified, this is also an issue for e.g. t-sparqlUpdate. Observe how the configuration of t-sparqlUpdate looks in DPU templates menu item and on the pipeline. On the pipeline the query box is expanded propery. 

Solution: DPU dialog (template configuration) should expand properly also when dislayed in DPU templates screen.

**Comment by skrchnavy** [comment]
To cherry pick to hotfix branch when finished.
@tomas-knap please review.

**Comment by skrchnavy** [comment]
cherry pick to hotfix branch
