### ISSUE TITLE
Frontend: Copy & Close discards changes without warning

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#240]
Frontend: Copy & Close in pipeline editor discards changes without warning

**Comment by tomas-knap** [comment]
@jakubklimek  Any steps to reproduce needed?

**Comment by jakubklimek** [comment]
Well... make changes to a pipeline, click copy& close and see what is saved.

**Comment by tomas-knap** [comment]
Solution: If there are changes, user should be warned

**Comment by mkl-eea-sk** [comment]
assign to me, as i was doing similar fixes recently

**Comment by tomas-knap** [comment]
One issue, see https://github.com/UnifiedViews/Core/pull/466, then it can be merged
