### ISSUE TITLE
Vaadin should be updated to 7.3

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#245]
Goal: Update Vaadin to 7.3 version. 

Problems which must be solved when updating: 

The following plugins needs to be updated/different should be used:
- refresher plugin 
- mytable plugin (Petr Skoda has detailed info)

Refresher plugin: 
As of
https://vaadin.com/forum/#!/thread/77100/7702171
je refresher not compatible s vaadin 7, aj tak sa tam používa.

Odporúčajú toto
https://vaadin.com/wiki/-/wiki/Main/Creating%20an%20UI%20extension
a upgrade na vaadin > 7.2
To len tak, že toto by som skúsil.
Tedy da se tato extension vyuzit pro exec monitor (udpate stavu pipeline) + pro logy? + pipelines (update last run, execution time etc.)?

**Comment by skrchnavy** [comment]
Extends #211 
is extended by #276

**Comment by skrchnavy** [comment]
@skodape shall be closed together with #276

**Comment by skrchnavy** [comment]
closed - to be included into v1.6.0. see #276 for details.
