### ISSUE TITLE
Architecture: Output symbolic names + Use Template Configuration not compatible

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#248]
![image](https://cloud.githubusercontent.com/assets/718827/5142033/87439dfe-717d-11e4-95cf-e95ed216e7de.png)

When the T-SPARQL Linkage are all the same DPU with "Use Template Configuration" on, they also all share the output symbolic name. The quality DPUs then don't change the symbolic names and therefore the merge to T-RdfToFiles won't work.

**Comment by skrchnavy** [comment]
@jakubklimek : Is this issue of Core or implementation of DPUs?

**Comment by mkl-eea-sk** [comment]
this is not an issue, use t-renamer

**Comment by jakubklimek** [comment]
Still an issue. It is not a good idea to solve this architectural symbolic name handling problem with 5 more dpus on this particular pipeline and all the others with similar layout.

This can be solved by autogeneration of symbolic names, which is what CUNI DPUs do. So the solution here is to use a different t-sparql DPU.

**Comment by mkl-eea-sk** [comment]
Agree. As this is already solved somewhere else, lets drop DPU which is 
wrong and use the one thats correct.

**Comment by tomas-knap** [comment]
Since new t-sparql DPUs will be used, see UV/Plugins #92, this will not be fixed
