### ISSUE TITLE
When creating mappings between data units, type of the data unit is not obvious

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#250]
Motivation: Currently, when creating mappings between data units, it is possible to select incompatible mappings, because only names are depicted in the lists, see below: 

![screen shot 2014-11-24 at 15 41 20](https://cloud.githubusercontent.com/assets/3014917/5166476/7d40a994-73f0-11e4-92cc-7bb495c67099.png)

Solution: 
1. Show not only data unit name, but also type (in brackets, RDF or FILE)
2. Extend the dialog with label "Only mappings between compatible data units are allowed, types of data units are in the brackets"
3. ensure that it is even not possible to select incompatible data types in the dialog (so the error should be thrown when the map button is pressed and edge is created between incompatible data types)

**Comment by skrchnavy** [comment]
I agree with item 1. (type of dataunit in brackets)
Regarding 2.: I propose to add combobox to filter data units in dialog based on type (All|RDF|Files).
Also when user selects incompatible data units, <MAP> button shall be disabled.

Cosmetic comment: To rename <Map> to <Add mapping> to be consistent with Delete mapping>

**Comment by skrchnavy** [comment]
Issue related also to #103
