### ISSUE TITLE
Frontend is unable to authenticate a user.

### ISSUE THREAD

**Issue by marcoony** [UnifiedViews/Core#251]
Frontend is unable to authenticate a user. 

logs: frontend - https://www.dropbox.com/s/8mgang6ggohl49n/frontend_25_11_2014.log?dl=0
backend - https://www.dropbox.com/s/hgnn2rfyhz3i9q2/backend_25_11_2014.log?dl=0

Only dpu T-anonymzation is running as you can see from backend's log.
frontend is waiting at cz.cuni.mff.xrg.odcs.commons.app.auth.PasswordAuthenticationProvider.retrieveUser(PasswordAuthenticationProvider.java:76)

probably on some Lock. Need to be analyse more. (if it is possible)

**Comment by tomas-knap** [comment]
Cannot reproduce
