### ISSUE TITLE
Two pipelines with same name cause frontend to crash when opening one of them

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Core#252]

**Comment by skrchnavy** [comment]
Is it OK to allow pipeline with same name as already existing?

**Comment by tomas-knap** [comment]
Yes, that is allowed. Frontend must not crash in these cases.

**Comment by skrchnavy** [comment]
Is there any requirement / use case for this feature? Please note we need also integration of UV into another systems and user could be confused when same name used few times.

**Comment by skrchnavy** [comment]
@tomas-knap please provide requirements for naming of pipelines. Be aware also of integration issues, when using UV in ODN, there is list of pipelines identified by name, so user is confused to see same pipeline twice. Id is not sufficient, user doesn't usually know pipeline ID.
You should consider also import of pipelines feature, how to cope with such situation? Shall be new pipeline created or pipeline with same name replaced?

**Comment by tomas-knap** [comment]
As I was testing last develop, when trying to save new pipeline with the same name, error occurs. Unique name is checked globally. Error should be also reported when pipeline is created over API (did not test). 

This is reasonable behavior - no two user in the system cannot prepare pipelines with the same.

Regarding import, I guess that the best is to ask the user what to do. As a result, user is informed about the conflict and may decide what to do (skip import of the pipeline, rewrite, create new)

**Comment by skrchnavy** [comment]
To allow unique name of pipeline systemwide is good (better then to allow duplicates of names), but has one disadvantage, when users doesn't see other's pipelines it could be difficult to find proper name when lot of pipelines defined. So there shall be mechanism to constrain naming of pipelines (prefix in name based on user for example, organisation name or another way). Or to allow pipeline naming per user/organisation.
Same could be then 'reused' in import of pipelines for automatic name conversion.

**Comment by mkl-eea-sk** [comment]
When uniqueness is per organization, changing access controls causes 
conflicts.

**Comment by skrchnavy** [comment]
Do we want to transfer pipelines from org. to org?
It is probably valid for simple model, when private/public is used then this is relevant but user can see other public pipelines.

**Comment by hanecak** [comment]
> To allow unique name of pipeline systemwide is good (better then to allow duplicates of names), but has one disadvantage, when users doesn't see other's pipelines it could be difficult to find proper name when lot of pipelines defined. So there shall be mechanism to constrain naming of pipelines (prefix in name based on user for example, organisation name or another way). Or to allow pipeline naming per user/organisation.

Simpler solution, sufficient to resolve this more quickly:
* UnifiedViews will enforce global uniqueness (as it seems to be doing as of now in 'develop' branch)
* oragnizations using UnifiedViews in multi-user and multi-organizations will setup "organizational measures", i.e. they will for example agree to use prefixes while naming pipe lines, to avoid naming conflicts between user groups which do not see each others pipelines
** this should be added as "hint" into UnifiedViews User Manual, into section dealing with "how to name you pipeline?"

**Comment by skrchnavy** [comment]
@mkl-eea-sk tested the behaviour and status is:
* frontend:
  * can't create pipeline with same name for one user
  * can't create pipeline with same name using Copy of
  * can't rename pipeline to already existing name using Rename
  * can't create  pipeline with same name in same (null) organization 
* via API:
  * it is possible to create pipeline with already existing name using CopyPipeline
  * it is possible to create pipeline with already existing name using CopyPipeline
* via import:
  * not tested

**Comment by skrchnavy** [comment]
@eea02 to align the code to work same way,

**Comment by skrchnavy** [comment]
#335 merged into develop branch, so closed
