### ISSUE TITLE
Support for PostrgeSQL as configuration database

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#253]
Currently it is MySql used as configuration database. It is expected to support also PostgreSQL.

(Migration from one type to another type is out of scope of this request).

**Comment by skrchnavy** [comment]
feature merged into develop in 17b9ab633e42ebef68534199b0d95a2ee89dc494

**Comment by skrchnavy** [comment]
needed to fix migration issue caused by this commit: 7560ba3 in MySQL support.

**Comment by skrchnavy** [comment]
inspiration: c6b662c

**Comment by tomas-knap** [comment]
@skrchnavy Please update the status, is it solved?

**Comment by mkl-eea-sk** [comment]
works, fixed.
