### ISSUE TITLE
Improvements of code for configuration database  

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#255]
- sequences in code are named, it is not necessary, databases names it automatically (could be problem with virtuoso support - solve later)
- use boolean type in MySQL instead of smallint for cases when boolean is used in objects

**Comment by skrchnavy** [comment]
is this commit  2122c1aaf990813eb086659cdccc06fc1783afb5  related also to this issue? (@pgo-eea-sk)

**Comment by mkl-eea-sk** [comment]
Yes , that commit is related to this issue.
But this issue is obsolete now. Sequences are back again, works with mysql and postgresql. Support for virtuoso as reldb has been dropped long time ago, and there is no reason to resurrect.
So close this issue as ‘wontfix’ and invalid.

**Comment by skrchnavy** [comment]
issu is closed as invalid (reason is above)
