### ISSUE TITLE
config frontend -  problem when property: frontend.log.keepDays is missing

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#259]
strange behavior when some sections is missing in config.
```
12:56:31,861 |-WARN in ch.qos.logback.core.joran.util.PropertySetter@78718955 - Failed to set property [maxHistory] to value "frontend.log.keepDays_IS_UNDEFINED".  ch.qos.logback.core.util.PropertySetterException: Conversion to
type [int] failed.
        at ch.qos.logback.core.util.PropertySetterException: Conversion to type [int] failed.
```

**Comment by Jan-Marcek** [comment]
Now, the properties doesn't exist at frontend. But the parameter: backend.log.keepDays exists at backend. is it ok?

**Comment by tomas-knap** [comment]
Property frontend.log.keepDays is prescribed in config.properties.sample, see: https://github.com/UnifiedViews/Core/blob/master/frontend/src/main/webapp/WEB-INF/config.sample.properties

But the error message should be improved, so that it is clear that the config property is missing in the config file

**Comment by Jan-Marcek** [comment]
@tomas-knap the issue is that there is no such a property at frontend. when you look at https://github.com/UnifiedViews/Core/blob/master/commons-app/src/main/java/cz/cuni/mff/xrg/odcs/commons/app/conf/ConfigProperty.java#L16 you will see the property ``` backend.log.keepDays. ``` but not ```  frontend.log.keepDays.```   "let's be united"

**Comment by skodape** [comment]
Just to add some information into discussion. The logback in frontend is (or at least I think it is) configured from:
https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/webapp/WEB-INF/classes/logback.xml

Where you can find use of that property - the error message is then probably raised by logback.

**Comment by Jan-Marcek** [comment]
In fact, we don't need any "special property in" frontend or backend config. To use logger xml could be enough, don't you think? To use some logger's xml is common in java world.

**Comment by tomas-knap** [comment]
The config param is already there, so I would suggest to just improve the message in the log, so that it is clear that frontend.log.keepDays is missing when there it tries to set up maxHistory
