### ISSUE TITLE
DataUnit working directory

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#262]
Name of working directory of DataUnit (especially FilesDataUnit) should be generated deterministically and should be self-describing. 

Aim of this issue is to change the working dir from:
exec_12123234732843729428
to something like:
37223/storage/dpu_1635/1
or something similar. Main idea  is to reflect pipeline-id, dpu-id and dataunit-id in the directory path. 
By this we can:
* remove random value in the directory name (path)
* made the structure more user friendly

Issue #158 is related to this but does not propose solution. This issue should be solved in virtuoso branch as a part of DataUnit updates.

**Comment by skodape** [comment]
Directories have been reworked in virtuoso branch now merged into develop. In case of further request on directory structure new issue should be created.

**Comment by skrchnavy** [comment]
closed - to be included into v1.6.0
