### ISSUE TITLE
UnifiedViews logo should be placed as the first menu item on the menu bar

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#263]
Currently, after updating the layout (see #170), logo appears on the home page, but not in the menu/above the menu (see screenshot below), there is name of the UnifiedViews instance (localhost in this case), but no logo:

![screen shot 2014-12-15 at 12 48 32](https://cloud.githubusercontent.com/assets/3014917/5435221/b770036c-8458-11e4-8c48-8002419fa67f.png)

Goal: Put the UnifiedViews logo to the menu bar (the space needed by the menu bar should not be increased if possible). Certain refactoring of the logo needed.

**Comment by skrchnavy** [comment]
Related also to #288 (is it in conflict or not?)

**Comment by tomas-knap** [comment]
#288 discribes the current issue of the develop branch. This issue is about proposing a way so that logo can return to the menu bar and it does not consume that much space.
