### ISSUE TITLE
It must be possible to see files being exchanged among DPUs (aka Files data unit browser)

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#266]
Currently, UnifiedViews supports browsing/querying of RDF data passed on RDF data units - see the Browse/Query tab of the execution record in UnifiedViews.
The goal of this task is to provide pipeline developers the possibility to see which files are passed between two DPUs using File data unit. Currently there is no way how to easily see which files are passed between two DPUs.

1) MUST: It must be possible to see the list of files being exchanged between DPUs
2) MUST: it must be possible to filter the list of files as needed
3) SHOULD: Provide possibility to preview the selected file (e.g. first 1000 lines).
4) SHOULD: Provide the possibility to download the selected file

This issues is motivated by: https://team.eea.sk/wiki/pages/viewpage.action?title=Requirements+for+tabular+transformers+and+loaders&spaceKey=COMSODE

See also: https://team.eea.sk/jira/browse/COMSODE-820

**Comment by tomas-knap** [comment]
Regarding the questions regarding the specification/design, please consult with @tomas-knap

**Comment by skrchnavy** [comment]
#221 extends this issue
