### ISSUE TITLE
Check dataunit releasing in frontend

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#267]
As described in https://team.eea.sk/jira/browse/COMSODE-200:

RDFQueryView.java:281
RDFQueryView.java:149
ManagableRdfDataUnit is created but never released.
It is mandatory to call .release() after work is done (especially problem for virtuoso data units).

Please check whether this is still relevant (w.r.t. to the currently prepared Virtuoso branch). If not, close with won't fix. 

Should be assigned to Petr Skoda.

**Comment by skrchnavy** [comment]
@skodape : ist this issue still relevant? it could be related to virtuoso support.

**Comment by skodape** [comment]
It should be quick-solved by:
https://github.com/UnifiedViews/Core/commit/2be71749a4ed2ddc4042bc2ef9c3e9b2d8b3509a
https://github.com/UnifiedViews/Core/commit/ab6f76bd1cd37e08bbd735036fd6d19fb5ae55dc

Problem is, that there is no space reliable enough to close the repository, also close and open too much will cause performance issue. For this reason the repository is auto closed after some inactivity (frost commit). 
Other problem was during redeploy - where repositories had not been closed and the lock prevented from browsing until full tomcat restart. I hope that this is solved by the second commit.

**Comment by tomas-knap** [comment]
There is a checker, which closes open connections, solves the problem with RDFQueryView
