### ISSUE TITLE
Filename and directory name of the uploaded DPU is taken from client request, not from pom.xml

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#268]
Originally https://github.com/mff-uk/ODCS/issues/1242:
"There is possible problem with new DPU filename and directory name.
Both filename and directory names on the server are derived from what the client sent in HTTP POST request as filename (which can be really any string!).

Even if we take into account, that this system will not be attacked by any hacker, regular user can hit errors in my opinion.

Consider server running on Windows machine using NTFS. According to http://en.wikipedia.org/wiki/Comparison_of_file_systems#cite_note-note-174-44
the NTFS can handle any character 'except NUL and \ / : * ? " < > |'.
Consider client running Linux with ext3, uploading a:-1.1.1.jar. What happens? I don't know, probably error. Will have to test.
See DPUModuleManipulator class.

But there is even more. The jarDirectory length limit in database is set to 255 characters. But there is a filesystem (ReiserFS for example) where the filename can be much longer (according to http://en.wikipedia.org/wiki/Comparison_of_file_systems it can be as long as 4096 characters). Even if the server filesystem can handle this, one will probably die on saving to the database, since directory name is derived from filename.

I would consider to leave using client sent filename to anything else except file-display-name for the user (and in the database the field would be long enough or the file-display-name would be abbreviated when saving). Let's use another file-real-name (generated random all filesystems safe string) field for the filesystem name (also stored in database)."

Solution: Filename & directory name should be taken from pom.xml

**Comment by skrchnavy** [comment]
I think directory name shall not be derived from request nor from manifest of DPU. There shall be strict place where all DPUs are installed and then a relative path to his place shall be stored in DB. 
Wrt. filename od DPU, it shall be named consistent to artefact, so even user name DPU wrongly, it shall be refused when not consistent or another option is to rename installed jar file according to manifest.
Also structure of directories could be managed by UV, using manifest.

**Comment by tomas-knap** [comment]
Yes, the idea is to use the last folder name and the dpu name as in pom.xml. The path to the last folder name is defined in the config file. @skrchnavy  do we comprehend it in the same way?

**Comment by skrchnavy** [comment]
If I understood, last folder name is relative path of DPU to the 'configured dir'. If yes then the same view.

**Comment by tomas-knap** [comment]
Yes
