### ISSUE TITLE
Backend tries to set every config value in DPU

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#269]
Any DPU can log message like 'Failed to set class value for: UnzipperConfig.decisionPrefix' for fields defined inside Config objects which do not have setters and getters programmed. This holds true also for static a/or final fields.
Or when Config class contains serialVersionUUID, backend tries to assign value to that one too.

Petr Skoda should be assigned to verify this issue is still relevant (even for the new configurator from CUNI helper, which will be used as official helper)

See also: https://team.eea.sk/jira/browse/COMSODE-402

![shot](https://cloud.githubusercontent.com/assets/3014917/5597929/5d622ef6-92ac-11e4-8536-36c0620cb472.png)

**Comment by skrchnavy** [comment]
Where is this DPU fixed? Will be included in milestone 1.0.0 or was it in some previous version alredy included?

**Comment by tomas-knap** [comment]
@skodape Please particularize

**Comment by skrchnavy** [comment]
@tomas-knap do we know version of core where it is fixed? Any commit or another reference?

**Comment by tomas-knap** [comment]
This would be hard to find, because it was fixed X months ago

**Comment by skrchnavy** [comment]
It was stated in March 2015 that it is fixed, expected it was included in release 2.0.0 (April 2015).
