### ISSUE TITLE
Refactoring of Unified views from ODCS to UV

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#270]
Update packages, maven properties, config attributes, etc.

Suggested changes:
* code:
 * packages: cz.cuni.mff.xrg.odcs.* -> eu.unifiedviews.*
 * ODCSApplicationServlet rename
 * comments in the code
* pom.xml files:
 * change any ODCS name in comments to UnifiedViews, change explicit package names
* root pom
```<groupId>cz.cuni.mff.xrg.odcs</groupId> 
<artifactId>odcs</artifactId>
<name>ODCleanStore</name>
<odcs.version> property name
```
* config.properties:
```
backend.name = ODCS
database.sql.dbname = odcs
```

* comments and other samples
 * ODCS->UnifiedViews

**Comment by tomas-knap** [comment]
most of the names already changes except of package names in Core and some classes in Core
