### ISSUE TITLE
Move mergers from Core to Plugins

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#273]
There is no output metadata graph for core DPU RDFMerger after debug execution.

**Comment by skodape** [comment]
The problem is that Merger does not create any metadata graph. It just reuse metadata graphs from other DPU. This create inconsistency and is confusing in debug.

We may consider the necessity of Mergers being core DPUs. The merge of graph/files can be done by proper modification of metadata graph (basically something like CopyHelper). 

Proposed change is to remove mergers from core and move them into plugin, where they would by implemented by simple ADD TO query over metadata graphs. The target graph of the query will be created metadata graph of merger, so the graph will be visible for debug.

**Comment by skrchnavy** [comment]
There is a reason to have mergers in Core not in Plugins, it requires access to core modules and there was intention not to allow other DPUs to access it.

**Comment by mkl-eea-sk** [comment]
Why not, may be. Mergers are relict of times, when add to query had to copy milions of triples.
i agree with petyr.

**Comment by tomas-knap** [comment]
I agree, remove mergers from core and move them into plugin.

**Comment by skrchnavy** [comment]
also documentation shall be updated accordingly (Readme.md in directory), do not forgot about version history there.

**Comment by skodape** [comment]
Mergers are now in Plugins repository. In case of any further note a new issue in Plugins repository should be created.

**Comment by mkl-eea-sk** [comment]
Just note: why not use mergers in two modes:
- debug - with copying triples to have metadata graph on output
- production - without copying (old mode), O(1) operation time

**Comment by skrchnavy** [comment]
@mkl-eea-sk please raise new enhancement for mergers
