### ISSUE TITLE
Vaadin version upgrade to 7.3.7

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#276]
Branch: https://github.com/UnifiedViews/Core/tree/feature/vaadinVersion
Problem: Commons-app exports old version of Vaadin (7.1.10). This is problem as new DPU's required  last version (7.3.7).
Solution: Fixe version in commons-app

**Comment by skodape** [comment]
Merged https://github.com/UnifiedViews/Core/commit/5511fe36ea1f631e337aa0c818cd3c72bca0f9c8

**Comment by skrchnavy** [comment]
@skodape consider also this commit ff3539e9091ec163ff428cbbd6fd03d6893e2fe4 to be 'merged' into develop (use it as inspiration). There are some additional changes when older vaadin upgrade was tested. (it is branch: https://github.com/UnifiedViews/Core/commits/feature/510_vaadin_migration_7.1.8_to_7.2.6 )

**Comment by skrchnavy** [comment]
closed - to be included into v1.6.0
