### ISSUE TITLE
Feature: Automatic schema install / update when UV installed or updated

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#280]
Currently it is necessary to run all update scripts for database manually.
It is expected to have schema updated when new version of UV is installed, when started it shall check if DB schema is is compliant with installed version. If not, all update scripts shall be started to migrate schema and data to proper version.
Also when database is not created, it shall be created automatically.

**Comment by tomas-knap** [comment]
@mvi-eea-sk What is the status of this task? Is it ready for testing? Or not finished?

**Comment by skrchnavy** [comment]
not finalized yet

**Comment by mvi-eea-sk** [comment]
https://github.com/UnifiedViews/Core/tree/feature/857_automatic_schema_install_or_update
ready to test, merged with develop branch few minutes ago ..
What does it do?
1. in backend: checks if db exist and initialized, if not ends backend. Starts update script if possible.
2. in frontend: if DB not initialized, through gui you can start db init after filling up admin username and password for mysql / postgres (not the user and pass from conf). After that refresh page and  you can work normally ... DB update scripts are checked on UV start.

**Comment by skrchnavy** [comment]
Update of requirements - to be more secure in upgrade
* in backend - it shall not start when schema is not compliant 
* in frontend - requires administrators username and password to run upgrade. (dialog shall also request UnifiedViews administrator username and password.

**Comment by mvi-eea-sk** [comment]
fixed: e6b8177

**Comment by tomas-knap** [comment]
@mvi-eea-sk What is the status of this task?

**Comment by mvi-eea-sk** [comment]
Changes that @skrchnavy proposed were implemented
+ was refactored little bit
+ the init and update DB scripts were removed from this module and are packaged from the db folder

Its ready for testing ...

**Comment by tomas-knap** [comment]
@mvi-eea-sk When certain non-trivial issue is done, please prepare pull request for me. Thanks.

**Comment by tomas-knap** [comment]
Is solved differently - see: https://github.com/UnifiedViews/Core/pull/485
