### ISSUE TITLE
Improve consistency of naming

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#284]
Throughout the repository you can encounter both "IntLib", "ODCS" and "UnifiedViews" as names of the tool. In some cases, all variants can be found in a single file (such as in front-end's [`config.sample.properties`](https://github.com/UnifiedViews/Core/blob/master/frontend/src/main/webapp/WEB-INF/config.sample.properties)). Improving consistency of naming and using "UnifiedViews" throughout the source code would help to avoid confusion among users. Related to #270 .

**Comment by skrchnavy** [comment]
Is duplicate of #270 ?

**Comment by jindrichmynarz** [comment]
As I indicate in the issue description I though it was only related to #270. However, upon closer reading of #270, I see it's rather a duplicate. I'm closing this.
