### ISSUE TITLE
Frontend: partial display of installation.name

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#288]
Using the develop branch (4d9a88b53f1d4f10243cb95a75861c1b419615fd) the front-end display of `installation.name` (from front-end `config.properties`) is visible only partially. The following image shows the display of "Test":

![screen shot 2015-02-05 at 15 55 18](https://cloud.githubusercontent.com/assets/198642/6062362/6d175656-ad4f-11e4-92be-b781c39becdb.png)

Upon closer inspection, this seems to be caused by the `.installationName` CSS class using `font-size: 25px;` while the `.v-label` CSS class restricts the height by `line-height: 18px`. A solution might involve dropping the `line-height` restriction.

**Comment by skrchnavy** [comment]
This is probably caused by some layout changes in virtuoso branch.

**Comment by skodape** [comment]
In fact this layout is no longer supported in Virtuoso branch as we removed the logo in order to give user more space for pipeline edit. Do we want to still solve this?
@jindrichmynarz Or is this about master branch? (then virtuoso-branch should have no effect).

**Comment by jindrichmynarz** [comment]
This is about the `develop` branch (4d9a88b53f1d4f10243cb95a75861c1b419615fd). Virtuoso branch, where this is a non-issue, is `feature/virtuoso`?

**Comment by tomas-knap** [comment]
Well, develop branch already includes feature/virtuoso, so you should not see such front-end display.

**Comment by tomas-knap** [comment]
Did you properly rebuild everything?

**Comment by jindrichmynarz** [comment]
Yes. I deleted previous builds and used the build from 4d9a88b53f1d4f10243cb95a75861c1b419615fd.

**Comment by tomas-knap** [comment]
I saw feature/virtuoso branch deployed and it was ok there. So this issue must be introduced when merging develop and feature/virtuoso branch.

**Comment by skrchnavy** [comment]
this is also valid in develop branch and also in released version 1.5.5.

**Comment by skrchnavy** [comment]
@eea01 please check this issue and fix if not big change in the code.

**Comment by eea01** [comment]
I was not able to reproduce described behavior with latest develop revision.
![test](https://cloud.githubusercontent.com/assets/10446114/6501620/062b1cd4-c31b-11e4-8c9f-34b346bc8b46.jpg)

**Comment by jindrichmynarz** [comment]
Confirmed. Using the latest commit from the develop branch (39f141be1884d4f77a799d45d067d0bf5b657e93), the issue disappears because the layout has been changed.
