### ISSUE TITLE
FilesDataUnit, "Can't delete storage directory" warning

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#289]
In case of non-debug execution with FilesDataUnit involved warning log "Can't delete storage directory" is generated by class eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit for no apparent reason (directory is not presented after pipeline execution).

**Comment by skodape** [comment]
Pull https://github.com/UnifiedViews/Core/pull/291

**Comment by skrchnavy** [comment]
#291 pull request closed
