### ISSUE TITLE
usage of PipelineView causes security issue - private pipelines are visible to other users

### ISSUE THREAD

**Issue by peterklimo** [UnifiedViews/Core#295]
PipelineView entity class does not implement OwnedEntity interface
Class cz.cuni.mff.xrg.odcs.commons.app.dao.db.DbAuthorizatorImpl does not add where clause to the queries related to pipelines and private pipelines are visible to all users.

**Comment by skrchnavy** [comment]
@skodape please check this issue, it is probably an inconsistency in security inside UV (private pipelines are differently presented based on method used to access pipelines).

**Comment by tomas-knap** [comment]
PipelineView was introduced to improve the responsiveness of the GUI. @skodape, OwnedEntity is missing there?

**Comment by skodape** [comment]
In fact it does not. It should not be hard to add. 

The reason is that the focus with view was more on performance also by that time it looks like the user would be removed.

**Comment by peterklimo** [comment]
this was fixed aleady by me in the sso_fixes branch. Adding OwnedEntity
does not help, because there is no column for owner in the view.

**Comment by skodape** [comment]
Yes that's true, you need to update the view and the POJO object unfortunately :( as only user name is accessible (I do not consider using the name to get User a solution now).

However @peterklimo is this than already fixed? As those are probably no new informations for you.

**Comment by peterklimo** [comment]
Yes it is fixed in feature/sso_fixes which hopefully will be merged into
the main branch in next few days

**Comment by skodape** [comment]
Great, thank you.

**Comment by tomas-knap** [comment]
@peterklimo, can you please link the commit solving this issue?

**Comment by tomas-knap** [comment]
Than we can close

**Comment by skrchnavy** [comment]
@peterklimo please provide commit number with this fix.

**Comment by eea03** [comment]
I have tested it on develop (after merge of sso_fixes) in user ownership mode and it works as expected;
I believe https://github.com/UnifiedViews/Core/commit/1d6862f2e4c5e6a9be4f985ee0f7cfc0be21b9a5#diff-f56ebdd053061e6c1cabc10606593e54 is fix of this issue
