### ISSUE TITLE
Message about duplicity of symbolic name on input data unit is confusing

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#297]
Log for duplicity entries:
Duplicity entry found for symbollic name: %s

Also it's just a log message, it should be an exception with proper Event/message. As now the pipeline fail for "no reason" on first sight.

**Comment by skrchnavy** [comment]
@skodape  Please update issue description (and subject) to understand where is the problem or how to reproduce it.

**Comment by skodape** [comment]
It's message generated by DataUnit during DataUnit "consistency check", it should be located in project dataUnit. 
Steps to reproduce: DPU produce two entries with same symbolic name. 

The fix should consists from two steps:
* Fix the message (simple, one line probably)
* Throw exception, or somehow propagate this to backend. As now pipeline fail there is only log with this text. There should be message (event).

But it's not high prior and I may be able to do this together with something else.

**Comment by jakubklimek** [comment]
![image](https://cloud.githubusercontent.com/assets/718827/6472965/55d2eada-c1f6-11e4-8cd9-4636463489f5.png)
Happend to me also. To reproduce, download an arbitrary file using HttpDownloader multiple times (2 or more copies of the same HttpDownloader) and connect the outputs to whatever DPU, which causes the merge which fails. As you can see, the resulting error message is completely useless, no one will understand that the problem is duplicate filename when merging FilesDataUnits

**Comment by tomas-knap** [comment]
Solution: Better error message should be thrown when merging of symbolic names failed, so that it is clear to the pipeline designer what happens.

**Comment by mkl-eea-sk** [comment]
Message in logs contains symbolic name. Is anything more requested?

![dupl](https://cloud.githubusercontent.com/assets/6399320/8545771/14487e44-24b2-11e5-9a18-22bd3b3ba9fa.png)

**Comment by skrchnavy** [comment]
@mkl-eea-sk is there any commit solving this issue? Is it already fixed or do we need further actions?

**Comment by mkl-eea-sk** [comment]
I did not attached commit number > I was unable to find any. But 3 persons have stated this is fixed, there is screenshot too.

**Comment by skrchnavy** [comment]
solved in 360be6fea6ce696628831aa4b35356109f73d9c1 and included in v2.1.0

**Comment by skrchnavy** [comment]
cherrypicked into v2.0.2 (commit 1186f4a8a8869e455fca25ab6f7b9e6a21bde4b9)

**Comment by skrchnavy** [comment]
Duplicate to #378
