### ISSUE TITLE
Frontend: Theming bug

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#302]
Develop branch, UnifiedViews theme set up. 

When I open e.g. execution monitor and hit F5, first this shows up:
![image](https://cloud.githubusercontent.com/assets/718827/6318683/2bcb72dc-baa0-11e4-8634-b39cd40b3a48.png)

then it gets refreshed to:
![image](https://cloud.githubusercontent.com/assets/718827/6318678/0821fc98-baa0-11e4-9a28-f8842a5e9473.png)
- with images missing.

Then sometimes after few minutes, some of the images get loaded.

**Comment by skodape** [comment]
As connection to this does the author of theme switching tested some more "Vaadin way"?

I mean the code that does this (theme switching and providing) is cool and nice, but it's more like from someone who knows pretty much about web but .. is not that interested in Vaadin-like solutions.

If Vaadin solution is not working (or does not exists) I would expect at least comment in code on proper place.

**Comment by tomas-knap** [comment]
Related with pull request: https://github.com/UnifiedViews/Core/pull/300

**Comment by tomas-knap** [comment]
@skrchnavy, I assigned @eea01 as he was responsible for pull request #300

**Comment by skrchnavy** [comment]
#305 pull request created

**Comment by tomas-knap** [comment]
Tested on PipelineList, switching the schemas works, when UV schema is set up, icons for pipeline actions are loaded properly.

**Comment by jakubklimek** [comment]
I also tested this and seems to be working.

**Comment by skrchnavy** [comment]
closed - to be included into v1.6.0
