### ISSUE TITLE
frontend.theme property in config.properties and backward compatibility

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#303]
In config.properties of frontend, frontend.theme property was added to support UV theme and also eDem theme. In order to be backward compatible, it should behave in the way: If frontend.theme is not found in  config.properties, it will not fail, but use default value - UV theme in this case. Motivation: Existing instances will not fail because of missing config.properties property. 

Relates to #300

**Comment by eea01** [comment]
This request forces implementation of hard-coded fallback UV theme (UnifiedViewsTheme), which we were trying to avoid. Generally speaking, deploying latest version of UV without latest configuration file changes is not recommended, since this would mean that latest version of UV supports all or some old configuration files, which is confusing.

**Comment by mkl-eea-sk** [comment]
upgrade of configuration is task for installation. app cannot support all old configuration options. i agree with previous comment

**Comment by tomas-knap** [comment]
Well, in case of new configuration options which is mandatory and needs decision of the user (cannot be decided by the tool), I agree with you that it has to fail because important option is missing. On the other hand, if the default option is clear (in this case UV theme is the default theme, eDem is the theme for one project), the tool must not require explicit definition of such default configuration. 

So it depends on the situation,but in this case, the default option is obvious and user should not be enforced to fill the value explicitly. If you run MS Word and do not specify that your default font is Arial, size 10, will it fail? No, it will use some reasonable default settings.

**Comment by eea01** [comment]
Default theme in [the configuration file](https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/webapp/WEB-INF/config.sample.properties) is UnifiedViewsTheme, no explicit user or tool decision is required.

**Comment by mkl-eea-sk** [comment]
tomas ale aj word (ak je rozumný) má tú informáciu, že arial 10 je 
default, napísanú v konfiguráku, ktorý sa tam predinštaluje. prakticky 
nikto to nerobí tak, že default hodnoty sú napísané v Jave  miesto toho 
aby nainštaloval userovi default konfigurák kde sú default hodnoty. 
nechápem akú to má výhodu, to čo chceš, že to bude v jave.
1. user so starým konfigom sa o novej option nedozvie
2. začnú sa mu kopiť zmeny
3. stratí prehľad
dokoncia linuxové distros ti robia počas inštalácie balíka diff 
konfigurákov, aby si mohol fixnúť veci. celý svet funguje takto, len UV 
to bude mať v jave...

**Comment by tomas-knap** [comment]
@eea01 yes, default theme is UV, this is ok. 

Situation we are targeting is: 
- UV is installed using installer from release branch
- when new release is available, UV is updated using update packages - as part of the update process, new configuration options are added with default values

But the problem is that we do not have such situation now and we will not have such situation soon.

So, as a temporal solution, similarly as there was intention to automatically initialise DB and apply any updates in UV, there should be a support for updates in config.properties - In case of new configuration options, I would expect that if the configuration option is not found in the user's config.properties file and there is default value in config.properties.sample, such default value is used and, should be also written to the user configuration file. I am not talking about storing the config option in Java, this is not a good practise, I agree, because such default value is on two places.

**Comment by tomas-knap** [comment]
Even when the we reach the state when UV stable may be easily installed/updated from debian packages (which also includes update of the conf if needed), still, we will have certain amout of develop machines, where we will be running develop branch/test feature branches etc. In all these cases the feature described above saves couple of minutes per one deploy of an update.

**Comment by tomas-knap** [comment]
Propose the best approach how to deal with changes in config.properties in the future

**Comment by eea01** [comment]
Solving #302 is more important at the moment.

**Comment by tomas-knap** [comment]
Yes, thanks

**Comment by jindrichmynarz** [comment]
I would argue against using hard-coded configuration in Java, but instead I'd propose using something along the lines of [deep-merging multiple configuration files](https://github.com/clojure-cookbook/clojure-cookbook/blob/master/04_local-io/4-15_edn-config.asciidoc#using-multiple-config-files).

**Comment by skrchnavy** [comment]
@tomas-knap I think we shall close this issue if UV works with default theme even not defined in properties file.
For improvement of properties file processing, new issue shall be created. ( @jindrichmynarz  to comment)

**Comment by tomas-knap** [comment]
Closed, see follow-up issue https://github.com/UnifiedViews/Core/issues/533, which deals with better handling of config params
