### ISSUE TITLE
Frontend, Google Chrome: Focused text input's height too low to show accented capital letters correctly

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#304]
Using UnifiedViews from the develop branch, commit 4ed9b6172c3547924753de3e45621cce7332c327, when I focus on a text input field that contains capital letters with accents, the accents get obscured because of the low height of the input field. For example, the following text should read "IČO":

![screen shot 2015-02-24 at 13 38 48](https://cloud.githubusercontent.com/assets/198642/6349512/adf8a964-bc2b-11e4-9718-627417688e63.png)

I've tested this on Google Chrome (version 40.0.2214.115), Mozilla Firefox (version 32.0.3), and Safari (version 7.1.3). In these browsers the issue appears only in Google Chrome.

**Comment by tomas-knap** [comment]
Cannot reproduce with Chrome 44.0.2403.130 (64-bit)
