### ISSUE TITLE
Pipeline validation doesn't work

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#308]
Using the UnifiedViews from the develop branch (commit 4ed9b6172c3547924753de3e45621cce7332c327) pipeline validation doesn't work. When the "Validate" button is used, the following exception is shown:

![screen shot 2015-02-26 at 11 25 25](https://cloud.githubusercontent.com/assets/198642/6390173/5b636574-bdaa-11e4-93d8-cb248c95a7b3.png)

The same exception appears in the front-end logs:

```
11:29:14.093 [http-bio-8080-exec-4] DEBUG c.c.m.x.o.f.a.PipelineValidator - Mandatory input/output check FAILED for following:
!EdgeCompiler.dpu.output!
```

This is the case even for the simplest pipeline loading data from file and saving it as a file.

**Comment by tomas-knap** [comment]
Cannot be reproduced on d9213d09b86646d9bdc6d784d0c25680848b11f5

**Comment by skrchnavy** [comment]
version 2.1.3 fixes this based on test. Probably it is fixed in older version, to find proper version fix, tests are necessary.
