### ISSUE TITLE
Trim trailing whitespace when parsing *.properties

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#309]
Trim trailing whitespace when parsing *.properties configuration files (I encountered multiple problems with trailing whitespace in configuration files during installation of UnifiedViews.).

**Comment by Jan-Marcek** [comment]
please, provide stack trace. 

I assume that problem would be with encoding. Sometimes when a user move file from OSX to *nix or M$ then this happens.

**Comment by jindrichmynarz** [comment]
Has the `*.properties` parser been extended to strip trailing whitespace? I cannot reproduce this issue in 39f141be1884d4f77a799d45d067d0bf5b657e93.
