### ISSUE TITLE
Sesame version upgrade to 2.8

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#316]
Sesame 2.8 released:
http://rdf4j.org/
fixes many issues, should be tested first.

**Comment by tomas-knap** [comment]
Tasks: 
1) Try 2.8 on top of existing pipelines, observe the results. 
2) If OK, we may switch to 2.8

Motivation to go for 2.8.X: Martin would benefit from 2.8.X (support for JSON-LD)

Potential risks: 
  * All literals are now datatyped. A string literal with no explicit datatype is automatically inferred to be of type xsd:string. When serialising documents in some formats, xsd:string will no longer appear as the datatype for any string literals. All language-tagged literal are typed internally with the type rdf:langString, but this type should not appear in any serialised documents. A direct consequence of this is that all code written to handle Literal objects must check for the existence of a language tag before checking the datatype. In previous versions, the Literal datatype could be checked before checking for a language tag, as they were previously mutually incompatible.
  * RDF identifiers are now IRIs. Previous versions of RDF used the notion of an 'RDF URI reference'. This notion has now become obsolete: identifiers in RDF 1.1 conform to the IRI specification (RFC 3987). A direct consequence of this is that although many more characters (especially from non-Latin alphabets) are now allowed to appear in identifiers, certain characters that were previously allowed are now illegal. One such character in particular is the whitespace character. See the RDF 1.1 specification for more details.

Differences between 2.7.X and 2.8.X: 
http://rdf4j.org/sesame/2.8/docs/articles/upgrade-notes.docbook?view

**Comment by tomas-knap** [comment]
Regarding assignee, waiting for confirmation from Martin.

**Comment by skodape** [comment]
Pull request https://github.com/UnifiedViews/Core/pull/376 merged.
