### ISSUE TITLE
Cryptography support implementation

### ISSUE THREAD

**Issue by eea01** [UnifiedViews/Core#320]
Add cryptography support for sensitive data (DPU configurations and passwords in configuration files).

**Comment by eea01** [comment]
Requesting approval.

**Comment by skrchnavy** [comment]
pull request #323 not approved, new version is planed to be provided

**Comment by eea01** [comment]
Requesting approval.

**Comment by tomas-knap** [comment]
See: https://github.com/UnifiedViews/Core/pull/338

**Comment by tomas-knap** [comment]
See the comments: https://github.com/UnifiedViews/Core/pull/338

**Comment by eea01** [comment]
Waiting for approval.

**Comment by eea01** [comment]
Waiting for approval.

**Comment by eea01** [comment]
Waiting for approval.

**Comment by tomas-knap** [comment]
Will test by tomorrow morning latest

**Comment by eea01** [comment]
Merged into develop.
