### ISSUE TITLE
DEV documentation: to explain 'Pipeline' 

### ISSUE THREAD

**Issue by hanecak** [UnifiedViews/Core#330]
Page "Basic concepts for creating new Data Processing Units (DPUs)":

https://grips.semantic-web.at/pages/viewpage.action?pageId=52564333

explains what is "DPU", "DPU Configuration", "DPU Template", "DPU Instance", "Data Unit". Then sort of jumps to "Pipeline execution - DPU Context", leaving "Pipeline" unexplained.

It would be nice to define/explain also "Pipleline" too, directly in that page.

**Comment by skrchnavy** [comment]
@tomas-knap / @hanecak  after changes of documentation, is this relevant?

**Comment by tomas-knap** [comment]
I will finalize and close

**Comment by tomas-knap** [comment]
Added to https://grips.semantic-web.at/display/UDDOC/Basic+Concepts+for+DPU+developers
