### ISSUE TITLE
Frontend: unbalanced quotes in pipeline names

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#331]
The UnifiedViews frontend displays pipeline name surrounded by unbalanced quotes:

![screen shot 2015-03-17 at 10 58 47](https://cloud.githubusercontent.com/assets/198642/6684803/e96f6798-cc94-11e4-85c5-5ddb3ae96297.png)

That is: `Pipeline detail for: ''Test'` (2 opening single quote and 1 closing single quote). It would be better if pipeline names were enclosed in balanced quotes.

Tested on a build from the develop branch, commit ad3d699b48b8441e3144d6749e24cf08ad081aa9.

**Comment by tomas-knap** [comment]
cannot reproduce

**Comment by skrchnavy** [comment]
fixed in 792c5f3c9f7d865957f69edf30d045f6a884e1c7
