### ISSUE TITLE
Frontend: Long pipeline name disables user to rename it

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Core#332]
As the down arrow is clipped out of browser view. See screenshot
![screenshot - 03172015 - 12 45 10 pm](https://cloud.githubusercontent.com/assets/6399320/6686617/9ed5e626-cca3-11e4-8674-93e12b3eb67c.png)

**Comment by tomas-knap** [comment]
already fixed

**Comment by skrchnavy** [comment]
fixed in 792c5f3c9f7d865957f69edf30d045f6a884e1c7
