### ISSUE TITLE
Branch sso_fixes: Concept of organizations cannot be anyhow used if SSO is disabled (standalone mode)

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#341]
Branch sso_fixes, 6b0ead485bdd048a4e3d2ea0e8aa463cd4781c9f 

Currently, many parts of the code operate with the concept of organizations. Organization is also available on contexts, in API methods. Also there is "organization" db table and other tables changed to reference "organization" table. So the proliferation of the concept of organization is high, so it is necessary to allow specification of organizations at least in a minimal way to justify the concept of organisation for standalone use of UV.

@peterklimo, think about some minimalistic solution, suggested approach: 

Steps to achieve minimalistic solution (talking about UV standalone mode): 
1) organization may be specified in config.properties (via e.g. organization=xx). If so, every pipeline created, executed, scheduled has reference to the organization stored in table organization (you already prepared such references in these tables). This applies only to new pipelines, executions etc. Admin has to adjust link to the organization for the previously created pipelines, executions etc. if needed. If organization is not specified within config.properties, all references to organizations are NULL (in ppl_mode, exec, etc.)
2) if (ownership.type=organization) is specified in config.properties, it is checked that organization is defined in config.properties. If not, error is shown. 
3) implement in pipelineDao (one single filter) and check that all methods taking into account concept of organizations work as expected
```
    @PostFilter("hasPermission(filterObject,'pipeline.read')")
    @Override
    public List<Pipeline> getAllPipelines(String organizationName) {
        // TODO: Add filter to pipeline DAO, to return only pipelines with given organization
        return pipelineDao.getPipelinesForOrganization(organizationName);
    }
```
4) test that it works in UV standalone mode, with or without organization param in config.properties, with or without ownership.type=organization.

**Comment by tomas-knap** [comment]
The amount of work needed: 
1) add combo box to user details dialog
2) add column org_id to list of users
3) test that when SSO is disabled, the system can work with organizations stored in organization table.

**Comment by tomas-knap** [comment]
When time will be pressing to much, we can finish this also in 2.0.1 release, but it has to be done, so that the use of the concept of organizations in UV - standalone mode - may be justified.

**Comment by skrchnavy** [comment]
Do we need to support organizations? UV work without it and when we have SSO with organizations, it shall be treated as extension.

**Comment by tomas-knap** [comment]
Well, currently the support for organizations is done only partially - there is something like entity shared by organization, pipeline/execution may have link to organizaiton, there are facade methods getPipelines(Organization o), db table to represent organizations organization - all in sso_fixes branch. But with UV standalone, there is no way how to define organization. So the idea of this issue is to add minimalistic support for working with organizations (groups of users).

**Comment by tomas-knap** [comment]
*Update:* I think it should be enough to use some default organisation to which all users belong. We can add GUI support later on, but we should solve this:

1)  Organization should properly persist to db, so there shouldn't be transient
```
@Transient
    private Organization organization;
````
2) Method below should be properly implemented

```
@PostFilter("hasPermission(filterObject,'pipeline.read')")
    @Override
    public List<Pipeline> getAllPipelines(String organizationName) {
        // TODO: Add filter to pipeline DAO, to return only pipelines with given organization
        return pipelineDao.getPipelinesForOrganization(organizationName);
    }
``` 

3) test that methods properly handle organizations when SSO is disabled

**Comment by peterklimo** [comment]
new property 'organization' introduced in the properties file, which allows to test organizations concept. organization is pulled into the system during login procedure. see PasswordAuthenticationProvider
commit 11ebff3

**Comment by tomas-knap** [comment]
Implemented in a way that: 
- org may be defined in config.properties. If yes, and organization-mode is used, such org is used when pipelines are created, such org is also visible in pipeline view.
