### ISSUE TITLE
Configuration help wrong for locale

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#343]
In backend config in develop branch at the bottom you can see:
![image](https://cloud.githubusercontent.com/assets/718827/6799563/2ef1b348-d217-11e4-97e8-b3c751c392ac.png)

Clearly, the set value "en" does not match the example "en_US".

**Comment by jindrichmynarz** [comment]
Does the default value for `locale` need to match any of the examples? If both language tags with subtags (e.g., `en_US`) and without subtags (e.g., `en`) are supported, then I don't see any problem.
