### ISSUE TITLE
Change label of button "mapa" to "spojiť" at Edge detail

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#347]
![bug](https://cloud.githubusercontent.com/assets/5822680/6914705/7bb9bb14-d78d-11e4-93ce-0de975e50198.png)

**Comment by eea03** [comment]
Label changed to "Prepojiť"; Also all related labels changed

**Comment by skrchnavy** [comment]
cherrypicked into release branch
