### ISSUE TITLE
2.0.0-update.sql for postgresql is missing

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#350]
at https://github.com/UnifiedViews/Core/tree/master/db/postgresql/updates

**Comment by tomas-knap** [comment]
Assigned to @peterklimo as he was doing mysql update script. @skrchnavy to confirm

**Comment by peterklimo** [comment]
do we really need an update script or postresql ? do we have an
installation with postgresql with real data which have to be retained
during installation ?

**Comment by skrchnavy** [comment]
we do need it.

**Comment by peterklimo** [comment]
all you need is love, you can find it in commit b467eae :D
