### ISSUE TITLE
Missing properties in backend config.sample.properties

### ISSUE THREAD

**Issue by eea01** [UnifiedViews/Core#352]
Add missing properties also to the [backend config.sample.properties](https://github.com/UnifiedViews/Core/blob/develop/backend/conf/config.sample.properties).

`
cz.cuni.mff.xrg.odcs.commons.app.conf.MissingConfigPropertyException: Config is missing property: ownership.type.
`

**Comment by tomas-knap** [comment]
Please use https://github.com/UnifiedViews/Core/blob/master/frontend/src/main/webapp/WEB-INF/config.sample.properties before adjusted
