### ISSUE TITLE
Export/Import v2

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#356]
**Goal:**
User needs to be able to import exported pipelines even on systems which have newer versions of Core, API (DevEnv) or DPUs. But not vice versa. 

In other words: 
It should be possible to import pipeline using older version of DPU then the version of the DPU being available on the target system

Details: 
https://team.eea.sk/wiki/pages/viewpage.action?pageId=113837857

User stories 81 - 85
[sto_82v1: Import pipeline from zip file containing no DPU JARs](https://utopia.sk/wiki/x/BAFwAw)

*\* Time needed to be solved: 3-5 MD**

**Further constraints regarding export/import and same names of DPU templates:**
1) When importing 3rd level DPU template, if the 3rd level DPU with the same name and same JAR file/parent already exists, the import of the DPU template will fail. If there is 3rd level DPU template with a different parent, there is no problem. 
2) When importing 2nd level DPU template, if the DPU template with the same name exists, the import will fail
3) When importing 2nd level DPU template, if the DPU template with the same artifactID exists, the import will fail (so it is not possible to have two 2nd level DPU templates with different name but pointing to the same JAR file. Also it is not possible to have two 2nd level DPU templates with the different name but pointing to the same artifact, but different versions) (Motivation: currently, DPU JAR files are stored on the filesystem using artifactID/jar name, so allowing two different DPU templates pointing to the same JAR would be confusing when updating versions)
4) I can create two 3rd level DPU templates with the same name. I can do that, but it is not a wise decision. (Better approach would be to enforce unique names of 3rd level DPU templates within one 2nd level DPU template, but not needed now)

Current behavior is as follows:
1) holds, 2) has to be verified. 3) has to be verified,  4) holds

**Comment by tomas-knap** [comment]
Related: https://github.com/UnifiedViews/Core/issues/196
Related: https://github.com/UnifiedViews/Core/issues/187
Related: https://github.com/UnifiedViews/Core/issues/177

**Comment by jindrichmynarz** [comment]
I'm trying to import a pipeline that uses uv-t-filesToRdf-1.6.0.jar. The UV instance into that I'm importing the pipeline provides uv-t-filesToRdf-2.0.1.jar. Based on our prior conversation with @tomas-knap, I'd assume that uv-t-filesToRdf-2.0.1.jar should be able to handle configuration from uv-t-filesToRdf-1.6.0.jar. However, that is not the case. If I try to import this pipeline the uv-t-filesToRdf-1.6.0.jar is shown in the list of the "DPUs which are missing in system. Install them before import".

I'm using UV 2.0.2 installed via 1.0.1 version of the odn-simple Debian package.

**Comment by tomas-knap** [comment]
@skrchnavy  We should solve this issues and related issues in release 2.2.0, because if we do not solve it, it will cause lots of troubles in the future when migrating from one instance to another

**Comment by tomas-knap** [comment]
@jindrichmynarz Lets wait for solution of this issue, then we can test

**Comment by tomas-knap** [comment]
I think we meet this only partially. Will check what is addressed.
