### ISSUE TITLE
Delete debug resources subscreen on Settings screen is empty

### ISSUE THREAD

**Issue by eea03** [UnifiedViews/Core#359]
After commit 4d57eee4e0611d1ad2fd93df977a82bec69fd92f, where some unused and not working code was removed, "Delete debug resources" subscreen on Settings screen is empty after clicking the button; I suggest to remove this button and screen if there is no intension to use this for some purpose; Maybe @skodape as the author of this commit knows more why the code was removed and why the screen was left empty; Fix is very easy, I need just need to know if this screen is really useless now

**Comment by skodape** [comment]
@eea03: There is usage, but not the implementation. 
This screen can be used to:
* Delete temporary data in import-export directory.
* Delete debug data in working directory - files, local rdf storage.
* Delete debug data from Virtuoso, if it's used as a storage.

But in current state the screen is useless and it can be easy added if needed in the future. 

In every case @tomas-knap, should have a final word.

**Comment by eea03** [comment]
I agree that it can be easily added in the future so for now I think it should be deleted

**Comment by eea03** [comment]
@tomas-knap Could you please provide decision for this? Are we keeping an empty screen or are we removing it for now? Also eDemo permissions depend on this because we have a separate permission for displaying this screen so I need to know if we need it or we can remove it because there will be no screen; Thanks

**Comment by tomas-knap** [comment]
Remove the empty menu item. Reimplementation is planned in https://github.com/UnifiedViews/Core/issues/371

**Comment by skrchnavy** [comment]
cherry pick into hotfix branch 2.0.2

**Comment by skrchnavy** [comment]
decuided not to add it into v2.0.2

**Comment by tomas-knap** [comment]
For deleting import/export temp data, see: https://github.com/UnifiedViews/Core/issues/373. For deleting debug and working data, see: https://github.com/UnifiedViews/Core/issues/362
