### ISSUE TITLE
Frontend: incorrect label for edge detail

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#361]
When you use the latest develop version (791cdce39008b4553e068ba1e2f42a90b7001164), you can find that the edge detail button is incorrectly labelled with "Set name of DataUnit.":

![screen shot 2015-04-22 at 07 00 16](https://cloud.githubusercontent.com/assets/198642/7267587/af78c012-e8bd-11e4-8309-247583d3b02d.png)

The source of this bug is [here](https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/components/pipelinecanvas/js_pipelinecanvas.js#L1763). A correct label should contain something like "Edit edge mapping". Note: the resolution of this issue depends on the chosen approach to internationalization of the front-end.

**Comment by farky** [comment]
implmented in pull-request #398

**Comment by tomas-knap** [comment]
To be closed when https://github.com/UnifiedViews/Core/pull/398 is closed
