### ISSUE TITLE
Unexpected error when exporting unsaved pipeline

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#364]
When I create a new pipeline, don't save it and try to export it, I get an unexpected error

![image](https://cloud.githubusercontent.com/assets/718827/7270687/59c6f3c0-e8de-11e4-9ce5-f36826c50666.png)

**Comment by skrchnavy** [comment]
shall be done together with #356

**Comment by skrchnavy** [comment]
implemented in develop (commit: 7cf409069649fd43a1c36f35ee798d9ea85feb9d)
need to be reviews if can be closed.

**Comment by tomas-knap** [comment]
Tested, ok.
