### ISSUE TITLE
MySQL update script from 1.6.0 to 2.0.0 not working for other users than admin and user

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#365]
When I run
https://raw.githubusercontent.com/UnifiedViews/Core/develop/db/mysql/updates/2.0.0-update.sql
to update from 1.6.0, it stops at line 

```
INSERT INTO `usr_extuser` VALUES ((select id from usr_user where username='admin'), 'admin');
```
and produces
```
0	168	11:29:28	INSERT INTO `usr_extuser` VALUES ((select id from usr_user where username='admin'), 'admin')	Error Code: 1048. Column 'id_usr' cannot be null	0.000 sec
```

**Comment by jakubklimek** [comment]
This is caused by the instance not having "admin" and "user" users...
This is a bigger issue, the database script cannot presume existence of specific users as this is evidently not always the case.

However, it presumes admin (https://github.com/UnifiedViews/Core/blob/develop/db/mysql/updates/2.0.0-update.sql#L261) and user (https://github.com/UnifiedViews/Core/blob/develop/db/mysql/updates/2.0.0-update.sql#L262)

**Comment by jakubklimek** [comment]
One needs to change the script to create roles for existing users -> only High, not Urgent prio

**Comment by tomas-knap** [comment]
Jakub is right - the problem is that the update script for schema.sql depends on data, which is NOT specified in schema.sql (but rather in data.sql). So the correct variant will, for example, copy all users from usr_user to usr_extuser (leaving the suggested solution peter klimo who introduced usr_extuser table), but it MUST not rely on the fact that user with admin role is called "admin" in the target system

**Comment by skrchnavy** [comment]
@eea03 to provide feedback.

**Comment by eea03** [comment]
Well, I am not the author of this update script but I think this solution was not wrong. Many systems have default users, that must be present in system to work properly. I would expect this is also our case as creating these default users are part of installation process; However, for more adventurous users, I fixed the update scripts (both for MySQL and Postgres) as @tomas-knap suggested and there is no dependency on user names now;
