### ISSUE TITLE
config.sample.properties is not well documented

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#366]
https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/webapp/WEB-INF/config.sample.properties

I don't understand the comments for 

* ownership.type=user

I don't understend why this is in frontend's config
* master.api.user=master
* master.api.password=commander

**Comment by tomas-knap** [comment]
Please supplement explanation, as you did: https://github.com/UnifiedViews/Core/pull/312

Currently, master API is done in a way that it stands next to frontend/backend, it is also package as independent war. So Jakub is right that the best would be if API module has its own config.properties, specified in a similar way as in case of frontend. Obviously master.war can point to the same config.properties as frontend/backend, but it is not necessary, if the user does not want.

**Comment by skrchnavy** [comment]
@eea02  / @eea03  to provide feedback

**Comment by eea03** [comment]
ownership.type config property will be removed shortly (already removed in feature branch) so I don't think it is necessary to bother with this

As for master configuration, @eea02 should provide feedback

**Comment by eea02** [comment]
Currently Master API shares configuration with frontend. I agree that it would be best if each application uses it's own configuration. I think, that there is already a feature request for this.

**Comment by skrchnavy** [comment]
There is a possibility that in #431 solution would be to merge master and frontend into one jar to safe memory, so this issue could be obsolete then. Lowering priority

**Comment by tomas-knap** [comment]
the only problem was master section
