### ISSUE TITLE
Save or Discard changes popup window performs a default action instead of cancelling

### ISSUE THREAD

**Issue by eea04** [UnifiedViews/Core#370]
Scenario:
1. I'm editing a pipeline.
2. I click somewhere else (let's say "DPU templates" in menu) which brings up a popup (Save pipeline or Discard changes). So far so good.
3. Now when I click the little cross of modal popup window (I want to close it), the application surprisingly doesn't stay on the current screen but **proceeds to next screen (in our case: DPU templates screen) and performs the default action** (save the pipeline if I remember correctly).

I find this counter-intuitive. This behavior might lead to users' pipelines being saved when not intended to (this was my case on several occasions). Standard behavior in all types of GUIs that I observed is that cancellation of this kind of popup window leaves the user on current screen and their work is untouched. User must make an explicit choice whether to save or discard the changes.
I suggest this be changed to function in a way users are accustomed to.
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by eea04** [comment]
@skrchnavy please assign to appropriate user

**Comment by tomas-knap** [comment]
Yes, I came also to this couple of times. Agree with your proposal. 

Proposal:  If the user clicks the cross (Cancel), no action should be performed, cancellation of this kind of popup window leaves the user on current screen and their work is untouched

**Comment by tomas-knap** [comment]
Setting High prio, as this is important from the usability point of view

**Comment by eea04** [comment]
Great. And while we're at this, I would also suggest that hitting the Escape key could cancel the popup, instead of having to click.

**Comment by tomas-knap** [comment]
Yes
