### ISSUE TITLE
Export/Import - Delete any temp files created during export/import

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#373]
When pipelines/DPUs are imported/exported, any temp files created during such process (e.g. files where DPU templates are unzipped) must be deleted after finishing export/import.

Related with #356

**Comment by mvi-eea-sk** [comment]
forgot to clean up after replacing DPU template from its detail, with https://github.com/UnifiedViews/Core/commit/482dd3e3f2c8c4feb56d5265f21cff21b899e5b7 it should be complete
