### ISSUE TITLE
Frontend: Reset Pipelines list sorting to default

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#374]
Pipelines (clear sort missing - I am unable to remove sort by name):
![image](https://cloud.githubusercontent.com/assets/718827/7347459/369d662c-ece9-11e4-9b95-278d3d3149b9.png)
Execution monitor: (Clear sort works here)
![image](https://cloud.githubusercontent.com/assets/718827/7347481/5df44ec0-ece9-11e4-98e8-4c4bf65d9a38.png)

**Comment by skrchnavy** [comment]
For execution monitor it was implemented as #216

**Comment by tomas-knap** [comment]
Solution: Pipeline list should also contain "Clear sort" button, so that it is consistent with execution monitor and allows default order.

**Comment by mvi-eea-sk** [comment]
@tomas-knap button added

**Comment by skrchnavy** [comment]
branch feature/frontend_reset_pipeline_list_sorting_to_default
