### ISSUE TITLE
"Duplicate entry found" - Message must contain name of the duplicate entry

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#378]
Develop branch, 6994614e19a5df31d8bd146e3280c45815a6356a. Currently, when "duplicate entry found" error occurs during pipeline execution, the message looks as: 
![screen shot 2015-05-04 at 02 01 10](https://cloud.githubusercontent.com/assets/3014917/7447588/9e91da98-f201-11e4-8b4c-0f1f8f71686c.png)

To solve: Supplement %s with the name of the problematic entry

Priority: Giving it High prio as this error message appears in couple of pipelines in rather suspicious situations, but it is hard to debug without the proper error message.

**Comment by tomas-knap** [comment]
Discussing with Martin, whether @skodape may be allocated.

**Comment by skrchnavy** [comment]
@peterklimo to cherrypick into 2.0.2 hotfix branch
