### ISSUE TITLE
Problems with session IDs when SSO is used (was: UV behaves differently in Google Chrome and Mozilla Firefox)

### ISSUE THREAD

**Issue by OskarStoffan** [UnifiedViews/Core#379]
When accessing a pipeline, the URL displayed contains parameters in Firefox. In Chrome it does not. The behavior is correct only when the parameter is not contained in the URL. (both screenshots below were created in Chrome, the second one with the URL copied out from Firefox). 

Root cause of this problem: 

When SSO is used and UnifiedViews is accessed via URL in the form of IP address (not hostname), then, after logging in, CAS forwards UnifiedViews to URL in the form of hostname. As a result, UnifiedViews cannot find the previous session created for IP address and creates new, which is put as a parameter to URL. UnifiedViews does not expect that and behaves strange then. Not behaves the same in every browser

Note: If UnifiedViews URL is accessed using hostname, everything works as expected. 

@peterklimo has details

![1_uv](https://cloud.githubusercontent.com/assets/8984799/7413016/67f73390-ef48-11e4-92f9-eb223bcb39f7.png)
![2_uv](https://cloud.githubusercontent.com/assets/8984799/7413015/67f60f74-ef48-11e4-84a4-9b40a99d632e.png)

**Comment by skrchnavy** [comment]
based in test of OpenDataNode/open-data-node#92 it is closed and fixed in 2.0.2
