### ISSUE TITLE
Frontend: to be able to access particular scheduler directly via URL

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#384]
Currently Scheduler view is implemented to contain list of schedules and click on particular schedule just raise popup window with schedule details.

Proposed is to change the behaviour of scheduler view similar to execution monitor, to implement split view, left side contains list of schedules and right side contains details about selected schedule.
To access schedule with ID=2 would be possible using URL: ```https://<server>/unifiedviews/#!Scheduler/schedule=2```

(this issue is triggered from OpenDataNode/open-data-node#113)

**Comment by mvi-eea-sk** [comment]
inspired by the https://github.com/OpenDataNode/open-data-node/issues/113
it would be good add filter according to pipeline id
something like this: ```https://<server>/unifiedviews/#!Scheduler/pipeline=2```

even better would be: ```https://<server>/unifiedviews/#!Scheduler/pipeline=2/new```
which would:
* filter the table
* open window as when adding new scheduling rule with the pipeline already selected

So in catalog if pipeline is associated to dataset, user chooses action "Schedule" and can only set the actual scheduling rule, presses Save and can see all the scheduling rules for that pipeline

**Comment by skrchnavy** [comment]
#456 merged, closing

**Comment by skrchnavy** [comment]
@tomas-knap can we close issue? #456 merged, do you expect any issue here?

**Comment by mvi-eea-sk** [comment]
@pgo-eea-sk what are the new parameters added and how does the link look like? Can you write some examples?

bug?
1. I open link /unifiedviews/#!Scheduler/pipeline=64
2. click button to add new scheduling run / edit existing rule
3. click cancel button
4. the parameter isn't there anymore and all schedules are displayed

**Comment by skrchnavy** [comment]
@mvi-eea-sk  / @tomas-knap if the above problem persists and if you see it as a bug, please create issue.

Closing for now, included in release branch 2.2.0
