### ISSUE TITLE
Possibility to localize also description of the DPU template

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#387]
It should be possible to localize also description of the DPU in the similar way as DPU name. See: https://github.com/UnifiedViews/Core/pull/358, which solved localization of the name of the DPU template.

@eea04 Is this the expected behavior?

**Comment by eea04** [comment]
I don't see into details of this functionality, but high-level, yes, description should be localize-able as well, because it's visible to the user.

Additionally, I see some overlap between description and the newly added "about tab" functionality.

**Comment by skrchnavy** [comment]
We shall distinguish description in manifest and user defined.
Manifest description defines something similar to About tab (About tab is extension that shall include also some configuration details and other details). This could be localized.
User defined description is for user to make there notes.

First step shall be to define what descriptions we have and how to cope with it in UV.

And manifest description is if I remeber diplayed only in case DPU is loaded, so not necessary to store it in DB just display it (localized) when necessary.

**Comment by eea04** [comment]
In my opinion, similar to how DPU title field was handled, the end user should not be able do edit the description field on 2nd level DPU, only on 3rd level DPU.

**Comment by eea04** [comment]
Additionally..
I currently see two description fields on each DPU:
- description (currently user editable)
- description from JAR file
This might be another duplicity (in addition to the about tab)

**Comment by skrchnavy** [comment]
@tomas-knap please provide feedback how to solve the issue.

**Comment by skrchnavy** [comment]
@tomas-knap isn't this solved via About tab? Do we need another localization of description?

**Comment by tomas-knap** [comment]
Marking as invalid. Currently it behaves in the way that: 
- 2nd level DPU templates' descriptions are by default set to : "See DPU Template Configuration, About tab.", where it can be localized

So the description of the DPU is localizable by pointing to the About tab. 

Description from JAR is not localized, nevertheless, this is rather technical info for admins, not for the normal user
