### ISSUE TITLE
Align the way how time is depicted in UnifiedViews - frontend

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#393]
The way how date&times are depicted in frontend should be aligned. For example, Pipelines tab (Last execution time) - format of the time different, it depicts also timezone.

So the places depicting data&time should be checked and the format should be aligned, including
- Pipeline tab (last execution time)
- Execution Monitor - table plus logs
- Scheduler

**Comment by mbl-eea-sk** [comment]
Is this issue still actual? By me datetime appears properly for both sk and en locale (see screenshots) under each mentioned tab.

![loc_en](https://cloud.githubusercontent.com/assets/12254192/8745877/50f71f56-2c84-11e5-9dd8-dcaa8831c28e.png)

![loc_sk](https://cloud.githubusercontent.com/assets/12254192/8745878/50f7a700-2c84-11e5-820e-a0b454173e1a.png)

All occurences of date format setting use the same construction.
https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/components/PipelineStatus.java#L111
https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/details/LogMessageDetail.java#L37
https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/details/RecordDetail.java#L56

The following one uses another class to get locale but it's switch takes the same effect.

https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/views/Scheduler.java#L348

Please confirm if this is already OK or specify configuration that causes trouble.
