### ISSUE TITLE
Update scripts to schema.sql and data.sql should be two separated files

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#397]
The update script below updates schema.sql as well as data.sql. It should be separated to two update scripts - one for schema.sql, one for data.sql. Also in the future, schema.sql updates should not be in the same file with data.sql updates.

https://github.com/UnifiedViews/Core/blob/feature/permissionsRefactoring/db/mysql/updates/2.1.0-update.sql

**Comment by skrchnavy** [comment]
This requirement is related to https://github.com/UnifiedViews/Core/pull/382/files .

**Comment by peterklimo** [comment]
in which order you want to perform an update ? schema first and then data ?
how would you handle a situation where you need to drop a constraint first,
then update the data and then create a constraint again ?

**Comment by skrchnavy** [comment]
I agree with @peterklimo , in many cases it is not easy to split migration to
* extend schema
* add new data

Usually there is
* conversion of schema (alter, create, drop)
* migration of data (calculation, insert, delete)
and mixed.

So I see this requirement as invalid.
