### ISSUE TITLE
Cannot init MySQL database: FUNCTION unifiedviews.nextval does not exist

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#408]
Using version 3a5bfb90c94d2b599a8a7cc5ca3ed82e41dc9197 I tried to init MySQL database. I successfully executed schema.sql, but in data.sql, I get following error
```
0	268	16:36:19	INSERT INTO `permission` VALUES (nextval('seq_permission'), 'dpuTemplate.showScreen', false)	Error Code: 1305. FUNCTION unifiedviews.nextval does not exist	0.000 sec
```

**Comment by jakubklimek** [comment]
Should be "NULL" I guess... from the other rows

**Comment by skrchnavy** [comment]
To include this fix into 2.0.3, it have to be fixed in hotfix branch. Is it necessary to have it in 2.0.3? I understand this is MySQL issue so for OpenDataNode not relevant.
@tomas-knap  to comment.

**Comment by skrchnavy** [comment]
@eea03  / @tomas-knap I guess it requires also other changes in develop, so we can't isolate this bugfix into 2.0.3

**Comment by eea03** [comment]
Actually this bug has never been released, it was only in develop (commit https://github.com/UnifiedViews/Core/commit/3418b4045c3ef65458ac00e4265d8e6a04231f6e) so I don't see a reason to have it in 2.0.3; And this permission is used only by code in develop so there is no reason to have it in 2.0.3
