### ISSUE TITLE
DPU template is not deleted after copy and reconfigure

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#409]
Steps to reproduce

* to copy DPU template
* to change configuration of copy, not saving changes
* To delete this changed DPU and to confirm deletion
 * _Result: DPU template disappears - CORRECT_
* To select another DPU template
* UV asks to save changes, to confirm save
 * _Result: DPU template is back - WRONG_

**Comment by tomas-knap** [comment]
Cannot reproduce on develop be7554753fb1bb8cb4f0b624c135aeedea0294f6

It was probably solved by https://github.com/UnifiedViews/Core/commit/3385932b55ba744cd273f5f45d8e93a30cd7ea40

Closing, reopen if that re-appears
