### ISSUE TITLE
Replace DPU via master API deletes DPU instances in all pipelines

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#411]
When replacing DPU template using master API with force=true, all DPU instances of such template in all pipelines and also all DPU templates that has parent template are deleted.
It is only issue in develop branch, released version works OK.

Replace via GUI is correct.

Probable cause is this commit: 6994614e19a5df31d8bd146e3280c45815a6356a

**Comment by eea02** [comment]
Previous commit reverted and improved logging during DPU import.
