### ISSUE TITLE
UnfiedViews + Java 8

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#42]
Test unifiedViews on top of Java 8

Known problems for frontend: 
![screen shot 2014-04-22 at 2 15 56 pm](https://cloud.githubusercontent.com/assets/3014917/2764625/00c29fc6-ca18-11e3-9197-58b3deaf2fe6.png)

**Comment by skrchnavy** [comment]
@skodape: please update status

**Comment by jakubklimek** [comment]
Feature/virtuoso already runs with Java8 and Tomcat8

**Comment by skrchnavy** [comment]
Is it compatible with tomcat 7 and java 7? Have been also spring updated to newer version?

**Comment by jakubklimek** [comment]
Don't know about spring. And yes, it should also run with Java7 and tomcat7

**Comment by skodape** [comment]
With java 7 there is a problem with "javadoc" settings (main pom.xml). As java 8 threads javadoc warnings as fatal errors (compilation fail), this can be turn off by special option, but java 7 does not support this "option". 

There were no changes to spring version.

**Comment by tomas-knap** [comment]
uv.opendata.cz runs on Java 8. If it reappears, we will reopen
