### ISSUE TITLE
Compilation of the front-end fails on OSX

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#424]
When compiling UnifiedViews Core from the most recent commit in the develop branch (bd1ace5a754b87b9fb8794da215e82fd4a443765), compilation of the front-end fails. See the log of `mvn install` here <https://gist.githubusercontent.com/jindrichmynarz/8fa932add727fd866806/raw/install.log>.

**Comment by eea03** [comment]
I wasn't able to reproduce this. I executed build from Jenkins and also locally from latest develop branch and compilation suceeded in both cases

**Comment by jindrichmynarz** [comment]
I've done `mvn clean` before this `mvn install`.

**Comment by jindrichmynarz** [comment]
This seems to be platform specific, since I managed to compile the develop branch on Debian box with the following context:

```
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-4-amd64", arch: "amd64", family: "unix"
```

**Comment by jindrichmynarz** [comment]
@tomas-knap Can you try to compile the latest develop commit to see if this is an issue of OSX in general or just of my machine?

**Comment by tomas-knap** [comment]
It is ok in my case. It seems that problem is with 

```
jar:file:/Users/mynarzjindrich/.m2/repository/org/vaadin/addons/filteringtable/0.9.11.v7/filteringtable-0.9.11.v7.jar
```

But I do not know why

**Comment by jindrichmynarz** [comment]
After deleting `~/.m2/repository/org/vaadin/addons/` (and letting Maven to fetch these dependencies anew) I'm able to compile the latest develop version (i.e. bd1ace5a754b87b9fb8794da215e82fd4a443765). I'm closing this issue.

Side note: Don't forget to mention the required SQL update in v2.1.0 release notes.
