### ISSUE TITLE
Mysql schema.sql script is outdated

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Core#426]
This script
https://github.com/UnifiedViews/Core/blob/develop/db/mysql/schema.sql
does not contain changes from 
https://github.com/UnifiedViews/Core/blob/develop/db/mysql/updates/2.0.0-update.sql
(new tables etc).

Please synchronize.

**Comment by skrchnavy** [comment]
related to #425 , @eea03  to check if it was fixed or is it new issue.

**Comment by eea03** [comment]
Could you be more specific? Actually in the mentioned update script, some new tables and columns were added which were then removed in 2.1.0 version (remove of organization concept).
https://github.com/UnifiedViews/Core/blob/develop/db/mysql/updates/2.0.0-update.sql script should be synchronized with https://github.com/UnifiedViews/Core/blob/UV_Core_v2.0.0/db/mysql/schema.sql

Latest schema.sql (in develop) should be synchronized with https://github.com/UnifiedViews/Core/blob/develop/db/mysql/updates/2.1.0-update.sql

I think, in both cases scripts are synchronized so I don't see a problem here

**Comment by mkl-eea-sk** [comment]
Ok, thanks.
