### ISSUE TITLE
Mysql 2.0.0 update script contains error

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Core#427]
ERROR 1280 (42000) at line 63: Incorrect index name 'role_id'
in this script https://github.com/UnifiedViews/Core/blob/develop/db/mysql/updates/2.0.0-update.sql

**Comment by skrchnavy** [comment]
related to #425 , @eea03 to verify it was fixed there

**Comment by eea03** [comment]
I tested it and there is no problem;
On which database did you test it? This update script can be run only on database initialized by v. 1.6 scripts (https://github.com/UnifiedViews/Core/tree/UV_Core_v1.6.0/db/mysql)

**Comment by mkl-eea-sk** [comment]
I have been running this on develop week old database, well, it can happen in develop. Nevermind, works now. Only thing have to assure is that releases can be upgraded, develop is not an issue. Invalid from my side. Thanks.
