### ISSUE TITLE
DB update script of certain version cannot include file without version

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#430]
Update script of certain version cannot point to a file without version. 

In https://github.com/UnifiedViews/Core/blob/develop/db/mysql/updates/2.1.0-update.sql, ../data-permissions.sql is included, which has no version.

Solution: Files included from updates/2.1.0-update.sql must all have version.

**Comment by eea03** [comment]
Well what you are suggesting would mean to create new SQL script with permissions with version which would be exactly the same as the https://github.com/UnifiedViews/Core/blob/develop/db/mysql/data-permissions.sql;
There would be again duplicity which is so difficult to maintain and after each release this duplicity would increase.

But I understand your concern, in current situation you cannot take update script for specific version and matching permissions script.

But currently I don't know how to solve it without introducing tons of duplicity again. For MySQL this is one extra script . For PostgreSQL it's 2 extra scripts. These scripts would be exactly the same like existing (but these can and probably will change in future releases)

I will give it a thought how to best solve this

**Comment by skrchnavy** [comment]
@eea03 as agreed add common code also to update script, even duplicity is there

**Comment by skrchnavy** [comment]
closed, it is in release
