### ISSUE TITLE
Correct handling of invalid configuration in DPU template screen

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#433]
As reported in https://github.com/UnifiedViews/Plugins/issues/207, there is a different behaviour in menus Pipeline editor and DPU Templates. In menu DPU Templates, when I try to save invalid DPU configuration, after pressing Save button Error message is issued and configuration is reinitialized to last valid configuration. For example if I miss some character but make many changes in configuration, all changes are then lost. In Pipeline editor (pipeline canvas) in DPU config dialog, it works correctly. After pressing Save, error message is issued but invalid configuration stays untouched, so I have chance to correct it.

In case of DPU template screen, if incorrect DPU template conf is specified, the following error occurs and defautl conf is loaded (which causes that user loses whole conf):
![screen shot 2015-06-26 at 12 08 51](https://cloud.githubusercontent.com/assets/3014917/8375303/54f1a09c-1bfc-11e5-816b-f3eb4fb54a47.png)

Solution: In case of adjusting DPU configuration in DPU template screen, it should behave also correctly - if invalid DPU template conf is specified, error is shown, new conf is not saved,  and user can adjust the invalid configuration (he must not lose the invalid configuration, default configuration must not replace his invalid configuration). 

The different behavior may be observed e.g. on t-sparqlUpdate with NO query defined - in case of DPU configuration on pipeline canvas - it behaves correctly - user is requested to correct invalid parts of the configuraiton. In caes of DPU templates it just reports problem and loads default conf

**Comment by mkl-eea-sk** [comment]
When done, this DPU is good candidate for testing: https://github.com/UnifiedViews/Plugins/issues/207

**Comment by mkl-eea-sk** [comment]
To make this change visible, we have to rebuild all DPUs with new plugin-devenv (helpers)

**Comment by mkl-eea-sk** [comment]
https://github.com/UnifiedViews/Plugin-DevEnv/issues/57

**Comment by skrchnavy** [comment]
Core part fixed but requires changes in DPUs (to use new PDE). So planed for 2.1.2
