### ISSUE TITLE
improve licensing information in source code

### ISSUE THREAD

**Issue by hanecak** [UnifiedViews/Core#441]
UnifiedViews core is licensed using two set of licenses: GPLv3 and LGPLv3.

High level-overview of licensing, describing also what parts are actually LGPLv3 and what GPLv3 is mentioned in https://github.com/UnifiedViews/Core/blob/master/README.md#licenses .

But http://www.gnu.org/licenses/gpl-howto.html states that also *"The copying permission statement should come right after the copyright notices ... This statement should go near the beginning of every source file, close to the copyright notices."*

So, to improve licensing information as per FSF recommendations (to avoid potential legal difficulties, etc.) adding short copyright and licensing notices as comment at the beginning of all non-trivial source code files is needed.

**Comment by skrchnavy** [comment]
Based on gpl-howto, each java file in Core shall have this text in the beginning of file:

For GPL modules
```
    /*
   This file is part of UnifiedViews.

    UnifiedViews is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    UnifiedViews is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
    */
```

For LGPL modules
```
    /*
   This file is part of UnifiedViews.

    UnifiedViews is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    UnifiedViews is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with UnifiedViews.  If not, see <http://www.gnu.org/licenses/>.
    */
```

**Comment by mkl-eea-sk** [comment]
This task is blocked as the list of modules : https://github.com/UnifiedViews/Core/blob/master/README.md#licenses is outdated.

**Comment by skrchnavy** [comment]
Discussion with @hanecak results into conclusion: Core is now 'GPL v3'
*(PluginsDevEnv is 'LGPLv3')*

Readme.md shall be updated accordingly (to use modules as are now listed in root pom.xml)

**Comment by tomas-knap** [comment]
@hanecak 
Ok, except for module-test (which is in UnifiedViews/Core), which should be licensed under LGPL, because:
* it was licensed under such license up to now
* it is directly used by the DPU, when testing the DPUs during development. So in order to avoid any potential issues when module-test dependency remains in commercial DPUs, lets leave it under LGPL. 

Ok?
