### ISSUE TITLE
Frontend: when locale in config is "en" and host default locale is "sk" frontend starts in sk language

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Core#444]
Although I have
```
locale = en
```
in frontend.properties and this value gets loaded correctly, frontend starts in sk language when the Locale.getDefault() in Java returns sk locale.
It seems like frontent ignores the setting.

**Comment by Jan-Marcek** [comment]
also backend has property locale. Could frontend reads this one?

**Comment by mkl-eea-sk** [comment]
Lets let mr. @mbl-eea-sk  to solve it

**Comment by mkl-eea-sk** [comment]
Oh, great, he has done it.
