### ISSUE TITLE
Frontend: unnecessary save prompt in DPU templates view

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#448]
When you go to the DPU templates view and click to view detail of a particular DPU template, then click on another DPU template without changing anything in the template configuration *Unsaved changes* prompt is shown. Steps to reproduce are also provided by @eea02 in #301 [here](https://github.com/UnifiedViews/Core/issues/301#issuecomment-119946790).

However, I discovered that this occurs only for certain DPUs, which leads me to believe that it may be a bug in the given DPUs and not in the UnifiedViews/Core. If that turns out to be the case, then we should move this issue to the appropriate DPU repositories.

I'm using bd1ace5a754b87b9fb8794da215e82fd4a443765 and I was able to reproduce this behaviour for these DPUs:

* t-filesFilter
* t-filesFindAndReplace
* t-filesRenamer
* t-htmlCss
* t-rdfMerger
* t-rdfToFiles
* t-sparqlConstruct
* t-unzipper
* t-xslt
* t-zipper
* l-rdfToSparqlEndpoint
* l-filesToParliament

Some DPUs that **don't** trigger the *Unsaved changes* prompt:

* e-filesDownload
* t-filesToRdf
* t-tabular
* ...

Interestingly, using UnifiedViews in ODN 1.0.3 installed from the odn-simple Debian package, the behaviour is different (probably due to different versions of DPUs?). Most DPUs trigger this dialog. The ones that don't are mostly loaders, such as:

* l-filesToCkan
* l-rdfToCkan
* l-rdfToVirtuoso
* l-relationalToCkan

Plus, there are several transformers and loaders that don't trigger the prompt including:

* t-geonamesOrgToRdfFile
* t-relational
* e-skWhoisToRdf
* e-relationalFromSql

Can we identify the difference between the DPUs that trigger the prompt and those that don't trigger it? Is it an issue of the individual DPUs or of the UnifiedViews/Core?

**Comment by skrchnavy** [comment]
as described by @eea02 in [#301/post](https://github.com/UnifiedViews/Core/issues/301#issuecomment-119543806) it is relevant for all DPUs with fault tolerance and probably with other extensions.

**Comment by mkl-eea-sk** [comment]
connected to #301 (not duplicate, but same cause)

**Comment by mkl-eea-sk** [comment]
After clean install, this issue https://github.com/UnifiedViews/Core/issues/301#issuecomment-119542560 is relevant and we can fix this one.

If you are using UV and do not have fresh install, procedure to fix this on your installation:
1. open DPU which causes 'are you sure' dialog
2. do not change anything
3. click save
this way, new template configuration is saved, with addon configuration also, next time the dialog should not appear.

**Comment by mkl-eea-sk** [comment]
This pull request is for this issue: https://github.com/UnifiedViews/Plugin-DevEnv/pull/61

**Comment by mkl-eea-sk** [comment]
I have found that there exists at least one DPU, which will trigger error even after fixing this issue. This is due the fact, that the DPU configuration dialog does not comply to contract:
```
dialog.setConfiguration(defaultConf)
defaultConf.equals(dialog.getConfiguration());
```
so that the dialog, even if nothing is changed, does not return same configuration (in respect of equals, it does not have to be same class instance) as it was set to.
This applies to t-filesFindAndReplace (see bug https://github.com/UnifiedViews/Plugins/issues/273 )

**Comment by mkl-eea-sk** [comment]
The fix for this issue requires DPU rebuilding and re-releasing.
