### ISSUE TITLE
FileDataUnit - entry.getFileURIString() points to non-existing file due to using "//" instead of "/" in the file uri

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#449]
When accessing entry.getFileURIString() in xls2csv DPU (but this problem should appear also in other DPUs), I got: 

```
/Users/tomasknap/Documents/PROJECTS/ETL-SWProj/UnifiedView/Core/backend/working/exec_45/storage/dpu_35/0/%252Fdata%252F268381848687814613
```
Nevertheless, the file is on the file system under the URI: 

```
/Users/tomasknap/Documents/PROJECTS/ETL-SWProj/UnifiedView/Core/backend/working/exec_45/storage/dpu_35/0/%2Fdata%2F268381848687814613
```
So there is a difference - in one case there "//data//xxx" and in second case there is "/data/xxxx" at the end of the file URI string. 

To reproduce: 
1) checkout and import the DPU: 
https://github.com/mff-uk/DPUs/tree/master/dpu-domain-specific/cssz-xls2csv
2) add 2 e-filesDownload, which are interlink as below: 

<img width="649" alt="screen shot 2015-07-12 at 14 47 16" src="https://cloud.githubusercontent.com/assets/3014917/8637815/f40613a2-28a4-11e5-9f4c-a5d86db254c2.png">

3) Each of these two e-filesDownload DPUs is loading one XLS file from the [zip](http://leteckaposta.cz/483335043) 
4) Debug till xls2csv, you will see errors "Problem copying file" which are cause by trying to read file from wrong location (with // instead of / in the fileURI) 

Tested on 2.0.2 release. Was able to reproduce on laptop and uv.opendata.cz/unifiedviews

**Comment by tomas-knap** [comment]
Please confirm, whether you can reproduce. It is strange we did not reveal this issue earlier.

**Comment by mkl-eea-sk** [comment]
first please try not to mangle the file uri string and use this to obtain file object from it:
new File(URI.create(fileUriString)
but before mangling, just as the data unit returned it, so add the line above, just after this line:
https://github.com/mff-uk/DPUs/blob/master/dpu-domain-specific/cssz-xls2csv/src/main/java/eu/unifiedviews/cssz/Xls2csv.java#L100

mangling does not help when one uses Paths.get (https://github.com/mff-uk/DPUs/blob/master/dpu-domain-specific/cssz-xls2csv/src/main/java/eu/unifiedviews/cssz/Xls2csv.java#L134)

When this test fails, then we will should to investigate (until now, it is just correct usage of file URI string).



----- Original Message -----

**Comment by tomas-knap** [comment]
new File(URI.create(fileUriString) approach should be used.
