### ISSUE TITLE
Frontend: I cannot see the title of a pipeline

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#454]
For some reason, I cannot see the pipeline title in the latest master:
![image](https://cloud.githubusercontent.com/assets/718827/8667529/54533854-2a01-11e5-9b5e-8180260c4854.png)

**Comment by tomas-knap** [comment]
To reproduce: Create pipeline, save pipeline, edit pipeline - title is not visible. It happens only with EN localization. (as discussed with Jakub)

**Comment by mkl-eea-sk** [comment]
\/ arrow - this feature was requested by jakub :D (hiding of title and 
desc fields)

**Comment by jakubklimek** [comment]
No, this is something else.
This is how it looks like collapsed using the arrow (correct):
![image](https://cloud.githubusercontent.com/assets/718827/8668396/dcb09094-2a0a-11e5-9dc6-52919e1b8c19.png)
This is how it looks like collapsed using the arrow (bug):
![image](https://cloud.githubusercontent.com/assets/718827/8668409/f6503b26-2a0a-11e5-99f3-ea80909cbb08.png)

**Comment by tomas-knap** [comment]
Problem: 

SK loc:
PipelineEdit.pipeline.detail= <h3>Detail procesu: ''{0}''</h3>

EN loc:
PipelineEdit.pipeline.detail=<h3>Pipeline detail for: ''

**Comment by tomas-knap** [comment]
Problematic commit: https://github.com/UnifiedViews/Core/commit/dbdff21e6958776823709042a695258c2d584076

Only SK localization was changed!

**Comment by mkl-eea-sk** [comment]
fixed here
https://github.com/UnifiedViews/Core/commit/792c5f3c9f7d865957f69edf30d045f6a884e1c7

**Comment by tomas-knap** [comment]
Yes, but this is only in develop

**Comment by tomas-knap** [comment]
So release hotfix is needed

**Comment by skrchnavy** [comment]
will be part of 2.1.1

**Comment by tomas-knap** [comment]
yes, but that is not enough, must be ready by today, will prepare hotfix

**Comment by tomas-knap** [comment]
So summary is: We will have release 2.1.1 today (around 13h). In this release, it is solved: https://github.com/UnifiedViews/Core/commit/792c5f3c9f7d865957f69edf30d045f6a884e1c7
