### ISSUE TITLE
Update README - list of modules and licenses

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#461]
Add also description from unifiedviews.eu

**Comment by skrchnavy** [comment]
Related also to #441

**Comment by mkl-eea-sk** [comment]
I have updated list of modules already https://github.com/UnifiedViews/Core/pull/478/files#diff-04c6e90faac2675aa89e2176d2eec7d8L25

**Comment by tomas-knap** [comment]
Yes, may be closed when https://github.com/UnifiedViews/Core/pull/478 is merged
