### ISSUE TITLE
Frontend: Pipeline name isn't displayed

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#472]
After upgrading to UnifiedViews in ODN 1.1.0 I found out that the pipeline names are no longer shown:

<img width="157" alt="screen shot 2015-07-22 at 09 55 21" src="https://cloud.githubusercontent.com/assets/198642/8820662/cabaaebc-3057-11e5-81a3-21349cf1f536.png">

However, the pipeline's name is still shown in the expanded view:

<img width="611" alt="screen shot 2015-07-22 at 09 56 07" src="https://cloud.githubusercontent.com/assets/198642/8820677/f7131918-3057-11e5-9787-f4ed07a1b839.png">

Pipeline name should be visible in the default view as well.

**Comment by skodape** [comment]
For reference: https://github.com/UnifiedViews/Core/issues/454

**Comment by skrchnavy** [comment]
@jindrichmynarz can we mark this issue as duplicate of #454 ? (it was included in the release of UV2.1.1 that is not part of ODN 1.1.0 but as updated version).

**Comment by jindrichmynarz** [comment]
I'm sorry. I haven't found #454. I'm closing this issue now.

**Comment by jindrichmynarz** [comment]
@skrchnavy: This issue still appears in ODN 1.1.1. Should we reopen it?

**Comment by skrchnavy** [comment]
Please provide info into #454 with your screenshot and if possible also versions of jar files.

**Comment by jindrichmynarz** [comment]
Do you mean versions of the UV frontend and backend JAR files?

**Comment by skrchnavy** [comment]
Based on feedback via email, this was a bug in UV debian package where version 2.1.0 of frontend was installed.
