### ISSUE TITLE
Front-end: closing "Unsaved changes" warning should cancel closing

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#475]
When you have a pipeline with unsaved changes, click on "Close", the "Unsaved changes" warning is shown. Currently, if you close this warning, the pipeline is closed without saving the changes. In typical software, closing such prompt cancels the whole action; i.e. nothing happens. Can UnifiedViews be made to work the same way? That is, when the "Unsaved changes" warning is shown and user closes it, nothing should happen and the pipeline should be left open.

Context: UnifiedViews 2.1.0 from ODN 1.1.0 (via odn-simple Debian package).

**Comment by skrchnavy** [comment]
Isn't this duplicate of #370 ?

**Comment by jindrichmynarz** [comment]
Yes, it is. I was searching for "unsaved" and haven't found this issue. I'm closing this issue as duplicate.
