### ISSUE TITLE
DPU templates are created on the top level

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#487]
When I copy a DPU template, it is created on the top level of the templates hierarchy instead of being a child of the DPU it provides a template for. For example, if I copy e-distributionMetadata, the copy is not shown as the child of e-distributionMetadata, but rather the top level:

<img width="223" alt="screen shot 2015-08-04 at 18 13 42" src="https://cloud.githubusercontent.com/assets/198642/9065873/943bf6a2-3ad4-11e5-9b73-868849d00d75.png">

I noticed this only in ODN 1.1.1. ODN 1.1.0 does not suffer from this issue.

**Comment by skrchnavy** [comment]
This is strange because this was fixed in 2.1.1 as fix of #459

**Comment by tomas-knap** [comment]
Yes, this is strange, I am not able to reproduce it on UV/Core, develop, ffb64f26bb9c298b7f1dfc5ef789574a7b98a8d6

**Comment by jindrichmynarz** [comment]
Last week, we discussed this with @skrchnavy and found out that ODN 1.1.0 was accidentally released with UV 2.1.0. This was fixed.
