### ISSUE TITLE
Add support for debian packaging into Core repository

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#488]
Currently we have dedicated repository with debina packaging of UV (frontend and backend).
It is requested to move this build rules into Core repository to simplify release process and to avoid conflicts and bug in versions for dependencies.

**Comment by peterklimo** [comment]
a568b16

**Comment by skrchnavy** [comment]
To fix installation of osgi bundles provided by core without adding jars into repository.

code part to be improved:
https://github.com/UnifiedViews/Core/blob/feature/deb_packaging/debian/unifiedviews-backend-shared/pom.xml#L113-L121
