### ISSUE TITLE
Wrong directory path from OSGIModuleFacade at frontend

### ISSUE THREAD

**Issue by yyz1989** [UnifiedViews/Core#500]
Hi there,

I am installing unifiedviews 2.1.1 and I got the following errors when I start the frontend:

```
2015-08-14 09:55:24,266 [localhost-startStop-1] ERROR c.c.m.x.o.commons.app.module.osgi.OSGIModuleFacade - Wrong directory path: /unifiedviews/target/lib
2015-08-14 10:08:10,036 [http-bio-8080-exec-8] ERROR cz.cuni.mff.xrg.odcs.frontend.gui.views.Initial - Failed to load initial page text from external resource {}, using default text
```

By checking config file, I only found one relevant property:
```
# Configuration of DPU modules
module.path = /unifiedviews/target
```
However this path is for DPU modules and I don't know what it is looking for. It seems it wants to load some libraries. So I went to the source code and saw it just wants to load all libraries under that directory. 

Then I thought if it's running does not depend on any specific library at that directory, maybe we don't need to report it as an error.

Additionally, the second error is related to another property
```
# HTML file with text to be displayed on title UV page (optional); By default, text is taken from localized resource
#frontend.initial.page = {path to HTML file with custom title page text}
```
Since this value is optional, I also do not think that it can be considered as an error.

What do you guys think?

Thank you and have a nice day.

Regards,
Yang

**Comment by Jan-Marcek** [comment]
Hi Yang,
How did you do installation of frontend? via debian packages?
Thanks

Regards, 
Jan

**Comment by yyz1989** [comment]
@Jan-Marcek 
Hi Jan,

Thank you for your reply.

I downloaded the source code of release 2.1.1, then build with "mvn clean install" and put it into tomcat.

Regards,
Yang

**Comment by Jan-Marcek** [comment]
Okay then. You have to do some manual configuration according this https://grips.semantic-web.at/display/UDDOC/Installation+Guide. There is also way how you can install unifiedviews from debian package. If you are trying to install for the first time I think this is best way.

However, 
I think ```module.path``` is wrong set. Please try to create path and update your frontend.properties
The steps to produce:
```
mkdir -p /var/lib/unifiedviews/common
# be aware that user who runs frontend has to have a permission to write.
```
then change your frontend.properties
```
module.path = /var/lib/unifiedviews/common
```
You have to change backend.properties in same way.

The property ```frontend.initial.page``` is optional. It shall work without it.


Regards, 
Jan

**Comment by skodape** [comment]
Hi Yang, 
just to add a note to the target/lib,  "default" content of this directory can be found in 
{repository root}/target/lib

Libraries in this directory are DPU's dependencies. The default libraries are dependencies of some core DPUs (Plugins).
If you try to for example import t-tabular without the lib directory you should get an exception about missing package.
Note that the content of this directory is loaded only on application start, so if you add a new library you have to restart UV.

We should consider update of the module.path property description, at least as output of this issue.

Regards,
Petr

**Comment by yyz1989** [comment]
@Jan-Marcek 
Hi Jan,

Thank you very much for your suggestion. I didn't install from the debian package because it integrates with an SQL server but I need them to run in separated environments.

I am following the guide from that page.

1. unifiedviews.war is in tomcat webapps folder
2. frontend property file defined
```
frontend.log.directory = /var/log/unifiedviews
general.workingdir = /unifiedviews/backend/working
module.path = /unifiedviews/target
and environment variables for postgres and virtuoso
```
3. setenv.sh at tomcat binary folder pointing to property file
```
#!/bin/sh
CATALINA_OPTS="${CATALINA_OPTS} -DconfigFileLocation=/unifiedviews/config/frontend.config.properties "
```
4. assign full permissions to the required directories
```
chmod 777 /var/log/unifiedviews
chmod -R 777 /unifiedviews/target
```

I didn't see missing steps according to that manual. As for the module path, I think the location doesn't matter. Whatever we defined in the backend property file, the corresponding "dpu" directory will be created automatically by the backend and the frontend just points there. I didn't see problem as long as we keep two settings identical.

Is there anything else I am missing? Thank you very much for your help.

Regards,
Yang

**Comment by yyz1989** [comment]
@skodape 
Hi Petr,

Thank you very much for your suggestion. So it explains why I got exceptions when I load some DPUs! Maybe I create a symbolic link to "{root}/backend/target/lib"?

At the beginning, I checked the "lib" folder contained in the frontend war file and I see all libraries are inside, so I thought well, since all libraries are already there, why do we load them from another location? Then I thought that it should be used for another group of libraries which are optional :D

Let me try this and report the result to you later. Thank you in advance.

Regards,
Yang

**Comment by yyz1989** [comment]
@skodape 
Hi Petr,

Great! Everything is working fine so far, no error at all :+1: 

It also solves the problems when installing some DPUs :D

Thank you very much for your help.

Regards,
Yang

**Comment by yyz1989** [comment]
@tomas-knap Hi Tomas, I guess we should update the documentation for this issue accordingly. However I don't have edit permission for that confluence page. I will ask next week.

Have a nice weekend.

Regards,
Yang

**Comment by tomas-knap** [comment]
Yes, please update. Helmut should give you access.
