### ISSUE TITLE
Delete pipeline executions - wrong counting of number of deleted records

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#501]
As the pipeline executions are pruned (Settings ->Managed debug and working data -> Delete ), the number of deleted executions does not reflect the reality. In my case I did: 

1) List pipeline executions: 
<img width="1643" alt="screen shot 2015-08-14 at 18 07 01" src="https://cloud.githubusercontent.com/assets/3014917/9278218/9e3e65b2-42af-11e5-8d47-d9de14196ba5.png">
2) Running pruning of executions (take not of "number of records deleted"): 
<img width="411" alt="screen shot 2015-08-14 at 18 07 17" src="https://cloud.githubusercontent.com/assets/3014917/9278229/b28933d0-42af-11e5-8f3d-96aeecec9d61.png">
3) Listing pipeline executions again 
<img width="1646" alt="screen shot 2015-08-14 at 18 07 24" src="https://cloud.githubusercontent.com/assets/3014917/9278231/bbc43c10-42af-11e5-8827-a43537ef5f90.png">

So only one execution was deleted, but in step 2) it tells me that 3 records was deleted

**Comment by tomas-knap** [comment]
This also happend to @eea03 :

I have encountered an issue during testing. Status line is displaying 2times more deleted entries that actually was deleted.
When I have 2 executions, status says 4 entries were deleted.
When I have 3 executions, status says 6 entries were deleted.
I would expect status informs how many executions were deleted. Or does it have some other meaning?

Example where I had 3 pipeline executions and they were all deleted:
```
Stav: Hotovo (2015-08-12 13:04:05) Počet vymazaných záznamov: 6
```

**Comment by tomas-knap** [comment]
But it does not happen to @mbl-eea-sk :

I have tested this up to 5 executions (including debugged) and in each case the message was displayed correctly...

**Comment by tomas-knap** [comment]
Originally discussed in #362

**Comment by mbl-eea-sk** [comment]
Which DPUs did you use? In my case it was a simple test pipeline containing only e-filesDownload. First opinion - can this be caused by more DPUs connected into 1 pipeline?
The counter of deleted records is implemented here: https://github.com/UnifiedViews/Core/blob/a0d025a43dc2af3238e6e13689684a4bee176812/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/views/Settings.java#L1205-L1216

**Comment by eea03** [comment]
Well, te bug is obvious now, you are actually counting number of deleted dataunits.
Logical place to put counter increment is after this line:

  pipelineFacade.delete(fpe);

At this place you delete the execution from database and logically at this place also counter should be incremented.

This also explains my issue, I had pipeline with 2 DPUs - extractor + loader so 2 data units.
Therefore I always got 2times more deleted entries than I had executions

----- Original Message -----

**Comment by tomas-knap** [comment]
Just to support your findings: I had pipelines with 3 DPUs ;-)

Please fix that,  ask @eea03  if needed.
