### ISSUE TITLE
unable to edit and remove edges in Windows 8.1 + Chrome 44.0.2403.155

### ISSUE THREAD

**Issue by yyz1989** [UnifiedViews/Core#508]
Hi there,

I am facing a strange error today. I cannot edit and remove the edge between two DPUs. When I click an edge, the control panel does not appear. If you keep clicking everywhere within that area, sometimes and in some locations the panel appears occasionally but it does not respond.

The environment is Windows 8.1 and the latest Chrome 44.0.2403.155. With the same Chrome version but in Ubuntu, everything works properly. I don't know the reason. Maybe it is because of Vaadin?

Regards,
Yang

**Comment by tomas-knap** [comment]
This also happened to @jakubklimek sometimes. I did not face this issue. I guess this will be hard to reproduce. 

Does that happen always in the described environment? Or sometimes it works correctly and sometimes not?

**Comment by yyz1989** [comment]
@tomas-knap 
Here it's permanent. I cannot fix it. I reinstalled chrome, tested with another earlier version but it doesn't make difference.

**Comment by tomas-knap** [comment]
I have the same version of Chrome and it does not appear. I am using Mac OS X.

This should be either an issue with Vaadin and the Javascript generated or directly with the canvas component. 

@skrchnavy Do we have resources to test this in Chrome/Windows and try to fix the bug if it is in the canvas component?

**Comment by skrchnavy** [comment]
@yyz1989 do you have the installation available from the internet to test it? Where is UV installed (system and setup). Is UV working In another browser on the same system where your chrome doesn't work?

**Comment by yyz1989** [comment]
@skrchnavy 
Hi, yes I have. It is installed in Ubuntu 14.04 inside a Docker instance. But it is working fine in other OS/Browser combinations. Even in my Windows, if I use Firefox it will work properly.

**Comment by tomas-knap** [comment]
Note: the commit above was associated with this issue by accident
