### ISSUE TITLE
Failed to create DPU: DPU has unspecified type

### ISSUE THREAD

**Issue by spinque** [UnifiedViews/Core#510]
We are trying to make a bundle for a custom DPU and install it into an existing ODN deployment. ODN 1.1.0 (UnifiedViews 2.1.0), via "Create DPU Template" in the UV UI.

We get "Failed to create DPU: DPU has unspecified type".

However the DPU class is annotated with `@DPU.AsTransformer`
Where else should the type be specified?

The DPU code is available at https://github.com/spinque/odn-plugins/tree/feature/dpu-json/t-jsonDpu

**Comment by eea03** [comment]
Your DPU class `JSONDpu` should not implement `DPU` interface as `AbstractDpu` class already implements this interface. I think this is causing your problems

So https://github.com/spinque/odn-plugins/blob/feature/dpu-json/t-jsonDpu/src/main/java/com/spinque/odn/uv/transformer/jsondpu/JSONDpu.java#L38-L39 should go like this:

```
@DPU.AsTransformer
public class JSONDpu extends AbstractDpu<JSONDpuConfig_V1> {
```

**Comment by spinque** [comment]
Thanks for pointing that out.
Unfortunately it doesn't solve the problem. Same error.

**Comment by skodape** [comment]
Could you try to change the scope of API (<artifactId>uv-dpu-api</artifactId>) from compile to provided. 

Also I'm not sure about the java version specified by maven-compiler-plugin - are you really running UV on java 6?

**Comment by eea03** [comment]
Preferrably the dependency
```
<dependency>
    <groupId>eu.unifiedviews</groupId>
    <artifactId>uv-dpu-api</artifactId>
    <scope>provided</scope>
</dependency>
```
should be removed, none of UV plugins  has it in its dependencies and clearly it is causing this problem.
Check any DPU, e.g. https://github.com/UnifiedViews/Plugins/blob/UV_Plugins_v2.1.0/e-filesDownload/pom.xml

Also changing scope to provided will do the trick.

**Comment by spinque** [comment]
Indeed, removing that dependency solves the issue.
