### ISSUE TITLE
External visibility of pipelines - enhancement proposal

### ISSUE THREAD

**Issue by MartinTuchyna** [UnifiedViews/Core#511]
Could it be possible to add the possibility to view pipeline in read only mode also for external users without the need to log into the UnifiedViews? Simple html view, or document report with text and images would be sufficient on the beginning. This could help to share authors of the pipelines share, document and consult their structure the as well as possibly attract the future potential users evaluating which ETL they will choose to transform their resources.

**Comment by tomas-knap** [comment]
Currently it is possible to communicate via pipeline exports, see #356 for current issues with export/import

**Comment by skrchnavy** [comment]
It shall be possible to add new role and configure permissions for this. @peterklimo  to confirm.
