### ISSUE TITLE
Can't import pipeline with same name

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#528]
Import of pipeline rise an exception when same name has already been used in unifiedviews.
I think UV shall ask a user to change name of imported pipeline or ask for overwrite.

Version:  unifiedviews-webapp-shared: 2.1.3

**Comment by skrchnavy** [comment]
Isn't this duplicate of #523 ?

**Comment by Jan-Marcek** [comment]
Yes
