### ISSUE TITLE
Installing UnifiedViews from debian packages using mysql

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#537]
It should be verified that installation with mysql works correctly, see the problems encountered in https://github.com/UnifiedViews/Core/issues/536#issuecomment-146856305

Instlallation with PostgreSQL is fine

**Comment by Jan-Marcek** [comment]
it was tested and fixed by https://github.com/UnifiedViews/Core/commit/4d205ecf276cc0ed72b72e1db93d77223c5f6ac2

**Comment by tomas-knap** [comment]
Thanks!
