### ISSUE TITLE
Name of actor wrongly displayed if in unicode

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#540]
Name of Actor if in unicode is wrongly displayed see screenshot
![error_username](https://cloud.githubusercontent.com/assets/7057580/10629329/23524766-77ce-11e5-8351-25e25fe6f51d.png)

**Comment by eea03** [comment]
Could you provide more information?
What version of UV is this?
On which database?

We had this issue on test server and it was caused by PostgreSQL SQL_ASCII database encoding and non-ascii characters could not be converted.

Solution was to change database encoding to UTF-8.

**Comment by eea03** [comment]
The problem was that UV Frontend  (tomcat) did not run with UTF-8 encoding.
Solution was to add encoding to CATALINA OPTS:
```
CATALINA_OPTS=" -DconfigFileLocation=/etc/unifiedviews/frontend-config.properties -Dfile.encoding=UTF-8"
```
