### ISSUE TITLE
Slf4jSessionLogger namespace causes certificate mismatch

### ISSUE THREAD

**Issue by larjohn** [UnifiedViews/Core#571]
Hi!
I tried deploying UV from IntelliJ IDEA to a Tomcat 9 M1 server. 

I get a Java Security Exception that has to do with certificates mismatch of the org.eclipse.persistence package.

I noticed that if I completely removed the package from the commons module and refactored it inside a logging package (eu.unifiedviews.commons.logging) the deployment continued as intended.

**Comment by tomas-knap** [comment]
@larjohn Can you please share with us the pull request with your changes?

**Comment by larjohn** [comment]
I will, when time becomes available :)

**Comment by tomas-knap** [comment]
@larjohn Can you please provide the pull request?
