### ISSUE TITLE
Release - latest release tag 

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#575]
Latest release tag points to the release which was published latest. But imagine that 2.3.1 is published and then 2.2, which causes that latest release points to 2.2 which is wrong

**Comment by skrchnavy** [comment]
This is github way of displaying order of releases, date of release is taken from date of tag.

_At their core, Releases are based on Git tags. Tags mark a specific point in the history of your project, so they're a great way to indicate a Release. Releases are ordered by a tag's date in the following way:_
* _If it's an annotated tag, the tag object's date is used_.
* _If it's a lightweight tag, then the commit object's date is used_.

see https://help.github.com/articles/about-releases/ for mor information

**Comment by tomas-knap** [comment]
Yes, but it is a bit confusing for those who are looking for the latest release,

**Comment by skrchnavy** [comment]
Yes, it is but couldn't do anything in this repo. Or one possibility is to remove and add the tag back and reassign the release, but it changes the date of the release.
