### ISSUE TITLE
Maven Compile error due to Sass Compiler

### ISSUE THREAD

**Issue by mlukasch** [UnifiedViews/Core#577]
Hello 
when try to compile the Core-project via: mvn install
I get the error:
Updating theme VAADIN/themes/UnifiedViewsTheme
uv_app_1   | [ERROR] /app/repos/Core/frontend/src/main/webapp/VAADIN/themes/UnifiedViewsTheme/styles.scss could not be read!

This file styles.scss does not exist in the project. There is just a styles.css.

Any suggestions how I can compile the project even so?
Thanks

**Comment by tomas-knap** [comment]
Hi, which branch/tag did you compiled?

This is strange, as I did not encounter such error in the past and nobody was changing the styles for months.

**Comment by mlukasch** [comment]
Hello, thanks for your feedback. Im trying to install the debian-package but when I start the service via:
service postgresql start && \
service unifiedviews-backend start && \
service unifiedviews-frontend start
it says: 
`[ ok ] Starting PostgreSQL 9.4 database server: main.
[ ok ing unifiedviews-backend: .
[FAIL] Starting Unifiedviews-frontend: unifiedviews-frontend failed!

This is catalina.out:
`# cat catalina.out
Mar 30, 2016 2:27:10 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-127.0.0.1-28080"]
Mar 30, 2016 2:27:10 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-28009"]
Mar 30, 2016 2:27:10 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1043 ms
Mar 30, 2016 2:27:10 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Mar 30, 2016 2:27:10 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.56 (Debian)
Mar 30, 2016 2:27:10 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/unifiedviews/tomcat/Catalina/localhost/unifiedviews.xml
Mar 30, 2016 2:27:11 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/usr/share/unifiedviews/frontend/WEB-INF/lib/servlet-api-2.5-20081211.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Mar 30, 2016 2:27:11 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/usr/share/unifiedviews/frontend/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
14:27:19,755 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:27:19,755 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:27:19,756 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/share/unifiedviews/frontend/WEB-INF/classes/logback.xml]
14:27:20,782 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:27:20,812 |-ERROR in ch.qos.logback.core.joran.action.PropertyAction - Could not find resource [../config.properties].
14:27:20,814 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:27:20,820 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:27:20,864 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:27:20,983 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:27:20,988 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE_ALL]
14:27:21,053 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
14:27:21,055 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /var/log/unifiedviews/frontend//frontend.%d{yyyy-MM-dd}.%i.log for the active file
14:27:21,059 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3d2cdecb - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/unifiedviews/frontend//frontend.%d{yyyy-MM-dd}.%i.log'.
14:27:21,059 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3d2cdecb - Roll-over at midnight.
14:27:21,060 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3d2cdecb - Setting initial period to Wed Mar 30 14:27:21 UTC 2016
14:27:21,063 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:27:21,067 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ALL] - Active log file name: /var/log/unifiedviews/frontend//frontend.log
14:27:21,067 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ALL] - File property is set to [/var/log/unifiedviews/frontend//frontend.log]
14:27:21,069 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:27:21,069 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE_ERROR]
14:27:21,099 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
14:27:21,100 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /var/log/unifiedviews/frontend//frontend_err.%d{yyyy-MM-dd}.%i.log for the active file
14:27:21,101 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4cd700cd - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/unifiedviews/frontend//frontend_err.%d{yyyy-MM-dd}.%i.log'.
14:27:21,101 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4cd700cd - Roll-over at midnight.
14:27:21,101 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4cd700cd - Setting initial period to Wed Mar 30 14:27:21 UTC 2016
14:27:21,102 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:27:21,103 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ERROR] - Active log file name: /var/log/unifiedviews/frontend//frontend_err.log
14:27:21,103 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ERROR] - File property is set to [/var/log/unifiedviews/frontend//frontend_err.log]
14:27:21,104 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to WARN
14:27:21,104 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.persistence] to WARN
14:27:21,105 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.persistence.logging.metadata] to WARN
14:27:21,105 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
14:27:21,105 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:27:21,108 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE_ALL] to Logger[ROOT]
14:27:21,108 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE_ERROR] to Logger[ROOT]
14:27:21,108 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:27:21,110 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3775ba24 - Registering current configuration as safe fallback point

Mar 30, 2016 2:27:21 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
14:27:26.716 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.c.AppConfig - Loading properties file from ServletContext resource [/WEB-INF/config.properties]
14:27:26.739 [localhost-startStop-1] WARN  c.c.m.x.o.c.a.c.AppConfig - Could not load properties from ServletContext resource [/WEB-INF/config.properties]: Could not open ServletContext resource [/WEB-INF/config.properties]
14:27:26.740 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.c.AppConfig - Loading properties file from URL [file:/etc/unifiedviews/frontend-config.properties]
Mar 30, 2016 2:27:26 PM cz.cuni.mff.xrg.odcs.commons.app.conf.AppConfig postprocess
INFO: Using locale: en
14:27:30.119 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.m.o.OSGIModuleFacadeConfig - com.vaadin version: 7.3.7
14:27:31.245 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading libraries from: /var/lib/unifiedviews/common/lib
14:27:31.960 [File notifier server] INFO  c.c.m.x.o.c.a.m.i.FileNotifierClient - DPU's change watcher is running ... 
14:27:33.419 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.d.r.RelationalRepositoryManager - Unknown repository type, using default file mode
Mar 30, 2016 2:27:34 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/unifiedviews/tomcat/Catalina/localhost/unifiedviews.xml has finished in 23,565 ms
Mar 30, 2016 2:27:34 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/unifiedviews/tomcat/Catalina/localhost/master.xml
Mar 30, 2016 2:27:34 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/usr/share/unifiedviews/master/WEB-INF/lib/servlet-api-2.5-20081211.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Mar 30, 2016 2:27:34 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/usr/share/unifiedviews/master/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Mar 30, 2016 2:27:42 PM org.apache.catalina.core.ApplicationContext log
INFO: Spring WebApplicationInitializers detected on classpath: [org.glassfish.jersey.server.spring.SpringWebApplicationInitializer@9120689]
14:27:42,710 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:27:42,710 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:27:42,711 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/share/unifiedviews/master/WEB-INF/classes/logback.xml]
14:27:42,907 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:27:42,919 |-ERROR in ch.qos.logback.core.joran.action.PropertyAction - Could not find resource [../config.properties].
14:27:42,920 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:27:42,925 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:27:42,959 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:27:43,007 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:27:43,010 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE_ALL]
14:27:43,037 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
14:27:43,039 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /var/log/unifiedviews/frontend//master.%d{yyyy-MM-dd}.%i.log for the active file
14:27:43,041 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@2a32705b - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/unifiedviews/frontend//master.%d{yyyy-MM-dd}.%i.log'.
14:27:43,041 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@2a32705b - Roll-over at midnight.
14:27:43,041 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@2a32705b - Setting initial period to Wed Mar 30 14:27:43 UTC 2016
14:27:43,044 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:27:43,046 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ALL] - Active log file name: /var/log/unifiedviews/frontend//master.log
14:27:43,046 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ALL] - File property is set to [/var/log/unifiedviews/frontend//master.log]
14:27:43,047 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:27:43,047 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE_ERROR]
14:27:43,053 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
14:27:43,053 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /var/log/unifiedviews/frontend//master_err.%d{yyyy-MM-dd}.%i.log for the active file
14:27:43,054 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@556e7c01 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/unifiedviews/frontend//master_err.%d{yyyy-MM-dd}.%i.log'.
14:27:43,054 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@556e7c01 - Roll-over at midnight.
14:27:43,054 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@556e7c01 - Setting initial period to Wed Mar 30 14:27:43 UTC 2016
14:27:43,055 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:27:43,055 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ERROR] - Active log file name: /var/log/unifiedviews/frontend//master_err.log
14:27:43,055 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_ERROR] - File property is set to [/var/log/unifiedviews/frontend//master_err.log]
14:27:43,056 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to WARN
14:27:43,056 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.persistence] to WARN
14:27:43,057 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ALL
14:27:43,057 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:27:43,058 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE_ALL] to Logger[ROOT]
14:27:43,058 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE_ERROR] to Logger[ROOT]
14:27:43,058 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:27:43,059 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@488f5178 - Registering current configuration as safe fallback point

Mar 30, 2016 2:27:43 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
14:27:44.163 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.c.AppConfig - Loading properties file from URL [file:/etc/unifiedviews/frontend-config.properties]
14:27:44.168 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.c.AppConfig - Loading properties file from ServletContext resource [/WEB-INF/config.properties]
14:27:44.169 [localhost-startStop-1] WARN  c.c.m.x.o.c.a.c.AppConfig - Could not load properties from ServletContext resource [/WEB-INF/config.properties]: Could not open ServletContext resource [/WEB-INF/config.properties]
Mar 30, 2016 2:27:44 PM cz.cuni.mff.xrg.odcs.commons.app.conf.AppConfig postprocess
INFO: Using locale: en
14:27:45.373 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacadeConfig - Instance: FRONTEND 
14:27:45.375 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacadeConfig - Packages from config: sun.misc,sun.io,com.sun.nio.file
14:27:45.376 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.m.o.OSGIModuleFacadeConfig - com.vaadin version: 7.3.7
14:27:45.566 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacadeConfig - list of package to expose: 
14:27:46.073 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading libraries from: /var/lib/unifiedviews/common/lib
14:27:46.074 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/jena-osgi-2.13.0.jar
14:27:46.158 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/org.osgi.compendium-4.3.1.jar
14:27:46.168 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/libthrift-0.9.2.jar
14:27:46.171 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/jsonld-java-0.5.1.jar
14:27:46.175 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/jackson-annotations-2.6.0.jar
14:27:46.178 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/xmlsec-2.0.1.jar
14:27:46.186 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/jackson-core-2.6.0.jar
14:27:46.190 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/commons-codec-1.9.jar
14:27:46.194 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/org.apache.servicemix.bundles.commons-csv-1.0-r706900_3.jar
14:27:46.196 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/org.apache.servicemix.bundles.poi-3.11_1.jar
14:27:46.247 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/commons-lang3-3.4.jar
14:27:46.251 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/org.apache.servicemix.bundles.xmlresolver-1.2_5.jar
14:27:46.254 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/org.apache.servicemix.bundles.jsch-0.1.49_1.jar
14:27:46.258 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/org.apache.servicemix.bundles.junit-4.12_1.jar
14:27:46.262 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/httpcore-osgi-4.4.4.jar
14:27:46.267 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/jackson-databind-2.6.0.jar
14:27:46.272 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /var/lib/unifiedviews/common/lib/httpclient-osgi-4.5.1.jar
14:27:46.351 [localhost-startStop-1] DEBUG c.c.m.x.o.c.a.m.i.FileNotifierClient - File watcher registered for: /var/lib/unifiedviews/common/dpu
14:27:46.352 [File notifier server] INFO  c.c.m.x.o.c.a.m.i.FileNotifierClient - DPU's change watcher is running ... 
`
This is frontend.log:
`2016-03-30 14:27:26,716 [localhost-startStop-1] INFO  cz.cuni.mff.xrg.odcs.commons.app.conf.AppConfig - Loading properties file from ServletContext resource [/WEB-INF/config.properties]
2016-03-30 14:27:26,739 [localhost-startStop-1] WARN  cz.cuni.mff.xrg.odcs.commons.app.conf.AppConfig - Could not load properties from ServletContext resource [/WEB-INF/config.properties]: Could not open ServletContext resource [/WEB-INF/config.properties]
2016-03-30 14:27:26,740 [localhost-startStop-1] INFO  cz.cuni.mff.xrg.odcs.commons.app.conf.AppConfig - Loading properties file from URL [file:/etc/unifiedviews/frontend-config.properties]
2016-03-30 14:27:30,119 [localhost-startStop-1] INFO  c.c.m.x.o.c.app.module.osgi.OSGIModuleFacadeConfig - com.vaadin version: 7.3.7
2016-03-30 14:27:31,245 [localhost-startStop-1] INFO  c.c.m.x.o.commons.app.module.osgi.OSGIModuleFacade - Loading libraries from: /var/lib/unifiedviews/common/lib
2016-03-30 14:27:31,960 [File notifier server] INFO  c.c.m.x.o.c.app.module.impl.FileNotifierClient - DPU's change watcher is running ... 
2016-03-30 14:27:33,419 [localhost-startStop-1] INFO  c.c.m.x.o.c.a.d.r.RelationalRepositoryManager - Unknown repository type, using default file mode
`

**Comment by tomas-knap** [comment]
Hi, from the log it seems that it cannot find config.properties (configuration file) for frontend and for that reason, it fails.

```
14:27:42,919 |-ERROR in ch.qos.logback.core.joran.action.PropertyAction - Could not find resource [../config.properties].
```

**Comment by mlukasch** [comment]
Sorry can close this. My fault. Wrong file permissions on some tomcat file.
