### ISSUE TITLE
Tomcat server fails to start

### ISSUE THREAD

**Issue by mlukasch** [UnifiedViews/Core#579]
Hi sorry to bother you again.
But I have tried both installation methods: debian package installation & compiling the repo. Neither worked so far:
WHen installing the repo, I get:
22:05:16.079 [taskScheduler-3] ERROR o.e.p.logging.ejb - 2016-04-03 22:05:16.079--ServerSession(874105962)--
in catalina.out
I get always tomcat faile when calling: service tomcat7 start
Thanks for helping

**Comment by Jan-Marcek** [comment]
Please provide catalina.out log.

**Comment by tomas-knap** [comment]
Maybe related with #577?

**Comment by mlukasch** [comment]
Sorry can close this. Wrong file permissions on some tomcat file.

**Comment by mlukasch** [comment]
Sorry can close this. Wrong file permissions on some tomcat file.
