### ISSUE TITLE
Copy & Close (and probably Copy) in pipeline editor does not save or warn

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#58]
When editing a pipeline and clicking Copy (Copy&Close) the pipeline is not saved (copy is the copy of the preivous state and all changes are lost)

**Comment by tomas-knap** [comment]
Now there is in UV 2.1 explanation if you try to Copy & Close unsaved pipeline: 

![screen shot 2015-08-04 at 20 58 14](https://cloud.githubusercontent.com/assets/3014917/9069779/9b5039aa-3aeb-11e5-8451-7bc6d1b80f29.png)
