### ISSUE TITLE
Pipelines that are set to public cannot be switched back to private any more

### ISSUE THREAD

**Issue by yyz1989** [UnifiedViews/Core#581]
Hi, I also observed that when a pipeline is set to public it cannot be changed to private any more. The option becomes unavailable. See screenshot below:

![screen shot 2016-04-18 at 17 46 39](https://cloud.githubusercontent.com/assets/7029943/14610286/8e71cb82-058d-11e6-86ef-d4f2b911becb.png)

**Comment by tomas-knap** [comment]
This was decided as a feature in the past -  if at certain moment pipeline is switched to be private, what should we do with the pipeline executions, scheduled events etc. prepared by another user? 

I would suggest to mark that as won't fix for now. Related: https://github.com/UnifiedViews/Core/issues/580
