### ISSUE TITLE
JavaEE deployment option

### ISSUE THREAD

**Issue by martinfmi** [UnifiedViews/Core#626]
I am having a use case where I am trying to fit UnifiedViews in a JavaEE application server (in particular WebLogic) and I was wondering if there is a deployment option for that or how feasible it would be to adapt a custom version of UV to that otherwise ?

**Comment by tomas-knap** [comment]
Hi, there should not be any limitations regarding frontend/rest api (war applications), but backend is currently just a console application, so you would need to pack it inside the war application, which should be pretty straightforward.

**Comment by martinfmi** [comment]
Thank you for the clarification, Tomas.
Regards,
Martin
