### ISSUE TITLE
Wrong display of pipeline cancelled while waiting for conflicts

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#71]
![image](https://cloud.githubusercontent.com/assets/718827/3172303/ba86acd6-ebd3-11e3-8c8e-36936d29db7c.png)

ARES 900 was waiting for ARES 4900 to finish. I cancelled both. There is, however, no message in ARES 900 events nor logs and the pipeline status is "finished with warnings" instead of "cancelled"

**Comment by tomas-knap** [comment]
Cannot be reproduced
