### ISSUE TITLE
Conflicts dont work

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#72]
ARES 4900 and ARES 900 pipelines both have both pipelines in conflicts. One ARES 4900 pipeline got stuck (was still running and retrying) and then other ARES 900 and ARES 4900 instances were started by scheduler, all ended waiting for the first instance to complete. When I cancelled the first one, all the others started running simultaneously - ignoring the conflicts.

**Comment by tomas-knap** [comment]
Cannot be easily reproduced
