### ISSUE TITLE
Export: Could required libraries be packed as well?

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#77]
While exporting, I can pack settings, schedule and DPU JARs. Could we also pack required libraries so that I don't have to copy them manually?

**Comment by skrchnavy** [comment]
@jakubklimek do you see this as required behaviour?
If yes, @tomas-knap do you have idea how to support this?

**Comment by tomas-knap** [comment]
DPUs should be written in a way that they pack everything inside (for easy migration/installation). If some share library or third party library not included in the DPU bundle is used, during migration, such dependency has to be migrated manually. Migration of target/lib is not automatic for now.
