### ISSUE TITLE
SPARQL loader times out on internal.opendata.cz:8900 Virtuoso instance

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#80]
SPARQL loader times out when loading bigger data (> 1M triples) to internal.opendata.cz:8900 virtuoso instance.
Pipelines:
- gov.cz: Instituce
- gov.cz: Agendy
- Buyers profiles

**Comment by tomas-knap** [comment]
Closing as loader is not part of current release, and it has to be redone, see: https://github.com/UnifiedViews/Plugins/issues/83
