### ISSUE TITLE
Internal error when putting a SPARQL query in debug mode in an input DPU

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Core#82]
![image](https://cloud.githubusercontent.com/assets/4235208/3701477/98d2c2fe-13f2-11e4-870c-097e0671d931.png)

It appears after clicking on Run Query with the following SPARQL

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sukl: <http://linked.opendata.cz/ontology/sukl/>

CONSTRUCT {
  ?df a sukl:DosageFormConcept ;
    skos:inScheme sukl:DosageFormConceptScheme ;
    skos:prefLabel ?title ;
    skos:notation ?concateddfnotation ;
    sukl:hasRouteOfAdministration ?roa .
}
WHERE {
  ?row <http://purl.org/dc/terms/title> ?title .
  OPTIONAL {
    ?row sukl:hasDosageForm ?dfnotation .
  }
  OPTIONAL {
    ?row sukl:hasRouteOfAdministration ?roanotation .
  }
  BIND(IRI(CONCAT("http://linked.opendata.cz/resource/sukl/df/", IF(ISLITERAL(?dfnotation), REPLACE(?dfnotation, "[\\s\\+]", "-"), ""), IF(ISLITERAL(?dfnotation) && ISLITERAL(?roanotation) > 0, "-", ""), IF(ISLITERAL(?roanotation), REPLACE(?roanotation, "[\\s\\+]", "-"), ""))) AS ?df)
  BIND(CONCAT(IF(ISLITERAL(?dfnotation), ?dfnotation, ""), IF(ISLITERAL(?dfnotation) && ISLITERAL(?roanotation) > 0, " ", ""), IF(ISLITERAL(?roanotation), ?roanotation, "")) AS ?concateddfnotation)
  BIND(IF(ISLITERAL(?roanotation), IRI(CONCAT("http://linked.opendata.cz/resource/sukl/roa/", REPLACE(?roanotation, "[\\s\\+]", "-"))), IRI("http://linked.opendata.cz/resource/sukl/roa/UNKNOWN")) AS ?roa)
}

**Comment by tomas-knap** [comment]
Issue closed. It points to the instance of UV not running now. Also the sesame version and work with repository changed from that time. If problem is encountered once again, please create new issue with the current pipeline reference, current log message etc.
