### ISSUE TITLE
Refresh automatically stopped working

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#91]
When looking at the logs, refresh automatically stopped working. I did not see the current logs even when I closed and reopend the tab (probably problem in session). Petr saw fresher data then me...

![image](https://cloud.githubusercontent.com/assets/718827/3763677/5d85f316-18a6-11e4-87d5-8c21016ed8b1.png)

**Comment by tomas-knap** [comment]
Cannot be reproduced
