### ISSUE TITLE
Support for graph URI in debug view

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#95]
When quads are passed among DPUs, quads should be supported by the debug view.
![image](https://cloud.githubusercontent.com/assets/718827/3764007/31147780-18ab-11e4-8381-9e6392e94ae1.png)

**Comment by tomas-knap** [comment]
Extend the view, so that graph URI is also depicted

**Comment by tomas-knap** [comment]
Ask @tomas-knap for details regarding specification/design
